/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.examsuccess.view.cemester;

import edu.ijse.gdse37.examsuccess.view.batch.Delete_Batch_Panal;
import edu.ijse.gdse37.examsuccess.model.Cemester;
import edu.ijse.gdse37.examsuccess.model.Student;
import edu.ijse.gdse37.examsuccess.connecter.ServerConnecter;
import edu.ijse.gdse37.examsuccess.controller.SemesterController;
import edu.ijse.gdse37.examsuccess.view.admin.Delete_Admin_Panal;
import edu.ijse.gdse37.examsuccess.view.other.Relese;
import java.awt.Color;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashan Tharuka
 */
public class Update_Cemester_Panal extends javax.swing.JPanel {

    /**
     * Creates new form AddQ_Panel_Form
     */
    private Student stu;
    private String code;
    private Relese relese;

    public Update_Cemester_Panal(Relese relese) {
        initComponents();
        setSize(630, 510);
        this.relese = relese;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matchLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cemesterText = new javax.swing.JTextField();
        idText = new javax.swing.JTextField();
        updateButton = new javax.swing.JPanel();
        addLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(630, 510));
        setPreferredSize(new java.awt.Dimension(630, 510));
        setLayout(null);

        matchLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        add(matchLabel);
        matchLabel.setBounds(555, 319, 176, 44);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Update Cemester");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 40, 300, 55);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("ID No :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 110, 93, 42);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Cemester Name:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 180, 115, 42);
        jPanel1.add(cemesterText);
        cemesterText.setBounds(240, 180, 163, 37);

        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });
        jPanel1.add(idText);
        idText.setBounds(240, 110, 163, 37);

        updateButton.setBackground(new java.awt.Color(255, 255, 255));
        updateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        updateButton.setPreferredSize(new java.awt.Dimension(165, 40));
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateButtonMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                updateButtonMouseReleased(evt);
            }
        });
        updateButton.setLayout(null);

        addLabel.setFont(new java.awt.Font("Monotype.com", 1, 18)); // NOI18N
        addLabel.setText("Update");
        updateButton.add(addLabel);
        addLabel.setBounds(60, 0, 80, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/update.png"))); // NOI18N
        updateButton.add(jLabel16);
        jLabel16.setBounds(20, 0, 40, 40);

        jPanel1.add(updateButton);
        updateButton.setBounds(240, 250, 165, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/courseLine.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 40, 560);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        String code = idText.getText();
        relese.code = code;
        try {
            SemesterController semesterController = ServerConnecter.getServerConnecter().getCemesterController();
            if (this.code != code) {
                semesterController.releaseSemester(this.code);
            } else {
                this.code = code;
            }

            Cemester cem = semesterController.SearchCemester("id", code);
            if (cem == null) {
                JOptionPane.showMessageDialog(null, "Not Match");
            } else {
                if (semesterController.reserveSemester(code)) {
                    cemesterText.setText(cem.getCemesterName());
                } else {
                    JOptionPane.showMessageDialog(this, code + " is reserved");
                }
                
            }
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(Delete_Batch_Panal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Delete_Batch_Panal.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_idTextActionPerformed

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        try {
            Cemester cemester = new Cemester(idText.getText(), cemesterText.getText());
            try {
                SemesterController cc = ServerConnecter.getServerConnecter().getCemesterController();
                boolean isTrue = cc.updateCemester(cemester);
                if (isTrue) {
                    idText.setText(null);
                    cemesterText.setText(null);
                    JOptionPane.showMessageDialog(null, "Update Successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Update Fail ");
                }
            } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                Logger.getLogger(Update_Cemester_Panal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException | IOException ex) {
                Logger.getLogger(Update_Cemester_Panal.class.getName()).log(Level.SEVERE, null, ex);
            }
        } finally {
            try {
                SemesterController semesterController = ServerConnecter.getServerConnecter().getCemesterController();
                semesterController.releaseSemester(this.code);
            } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                Logger.getLogger(Delete_Admin_Panal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_updateButtonMouseClicked

    private void updateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseEntered
        updateButton.setBackground(Color.yellow);// TODO add your handling code here:
    }//GEN-LAST:event_updateButtonMouseEntered

    private void updateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseExited
        updateButton.setBackground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonMouseExited

    private void updateButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLabel;
    private javax.swing.JTextField cemesterText;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel matchLabel;
    private javax.swing.JPanel updateButton;
    // End of variables declaration//GEN-END:variables
}
