/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.examsuccess.view.cemester;

import edu.ijse.gdse37.examsuccess.view.admin.View_Admin_Panal;
import edu.ijse.gdse37.examsuccess.model.Cemester;
import edu.ijse.gdse37.examsuccess.connecter.ServerConnecter;
import edu.ijse.gdse37.examsuccess.controller.SemesterController;
import edu.ijse.gdse37.examsuccess.view.observerimpl.SemesterObserverImpl;
import edu.ijse.gdse37.examsuccess.view.other.Relese;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ashan Tharuka
 */
public class View_Cemester_Panal extends javax.swing.JPanel {

    /**
     * Creates new form AddQ_Panel_Form
     */
    private DefaultTableModel dtm;

    public View_Cemester_Panal(Relese relese) {
        initComponents();
        setSize(630, 510);
        dtm = (DefaultTableModel) view.getModel();
        dtm.setRowCount(0);

        try {
            SemesterController sc = ServerConnecter.getServerConnecter().getCemesterController();
            SemesterObserverImpl semester = new SemesterObserverImpl(this);
            relese.observerImplOb = semester;
            sc.addSemesterObserver(semester);

        } catch (NotBoundException ex) {
            Logger.getLogger(View_Cemester_Panal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(View_Cemester_Panal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(View_Cemester_Panal.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            SemesterController cc = ServerConnecter.getServerConnecter().getCemesterController();
            ArrayList<Cemester> cemesterList = cc.getAllCemester();
            if (cemesterList == null) {
                JOptionPane.showMessageDialog(null, "No Students");
            } else {
                for (Cemester ce : cemesterList) {
                    Object[] row = {ce.getId(), ce.getCemesterName()};
                    dtm.addRow(row);
                }
            }

        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(View_Admin_Panal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(View_Admin_Panal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        view = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(630, 510));
        setPreferredSize(new java.awt.Dimension(630, 510));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Cemester Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        view.setRowHeight(25);
        jScrollPane1.setViewportView(view);
        if (view.getColumnModel().getColumnCount() > 0) {
            view.getColumnModel().getColumn(0).setResizable(false);
            view.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 120, 540, 230);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("View Cemester");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 40, 300, 55);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/courseLine.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 40, 560);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 630, 510);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable view;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param message
     * updateMessage method
     */
        public void updateMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
}
