/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.examsuccess.view.admin;

import com.sun.java.swing.plaf.motif.MotifBorders;
import edu.ijse.gdse37.examsuccess.view.admin.MainAdmin;
import edu.ijse.gdse37.examsuccess.view.manage.ManageCourse;
import edu.ijse.gdse37.examsuccess.view.manage.ManageQuestion;
import edu.ijse.gdse37.examsuccess.view.manage.ManageExam;
import edu.ijse.gdse37.examsuccess.view.manage.SendNotification;
import edu.ijse.gdse37.examsuccess.view.setting.AdminSetting;
import edu.ijse.gdse37.examsuccess.view.student.MainStudent;
import edu.ijse.gdse37.examsuccess.connecter.ServerConnecter;
import edu.ijse.gdse37.examsuccess.controller.LoginController;
import edu.ijse.gdse37.examsuccess.view.manage.ViewAdminResult;
import edu.ijse.gdse37.examsuccess.view.other.Relese;
import java.awt.Color;
import java.awt.Frame;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ashan Tharuka
 */
public class Admin extends javax.swing.JFrame {

    private static String id;
    private static String userName;

    /**
     *
     */
    public boolean setting;
    private int xMouse;
    private int yMouse;
    private static Relese relese;

    /**
     * Creates new form Login
     *
     * @param id
     * @param userName
     */
    public Admin(String id, String userName) {
        initComponents();
        setLocationRelativeTo(null);
        setSize(1105, 700);
        this.id = id;
        this.userName = userName;
        /////////////////////////////////
        setting = false;

        if (relese == null) {
            relese = new Relese();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        minimizePanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        closePanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        manageAdminButton = new javax.swing.JLabel();
        manageStudentButton = new javax.swing.JLabel();
        manageExamButton = new javax.swing.JLabel();
        managePaperButton = new javax.swing.JLabel();
        sendMessageButton = new javax.swing.JLabel();
        viewResultButton = new javax.swing.JLabel();
        manageCourseButton = new javax.swing.JLabel();
        settingButton = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hostPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1105, 700));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        minimizePanel1.setBackground(new java.awt.Color(255, 255, 255));
        minimizePanel1.setPreferredSize(new java.awt.Dimension(40, 40));
        minimizePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizePanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizePanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizePanel1MouseExited(evt);
            }
        });
        minimizePanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/020739-rounded-glossy-black-icon-symbols-shapes-minimize.png"))); // NOI18N
        minimizePanel1.add(jLabel4);
        jLabel4.setBounds(10, 20, 20, 10);

        jPanel1.add(minimizePanel1);
        minimizePanel1.setBounds(1000, 10, 40, 40);

        closePanel1.setBackground(new java.awt.Color(255, 255, 255));
        closePanel1.setForeground(new java.awt.Color(255, 255, 255));
        closePanel1.setPreferredSize(new java.awt.Dimension(40, 40));
        closePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closePanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closePanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closePanel1MouseExited(evt);
            }
        });
        closePanel1.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/icon-nav-close.png"))); // NOI18N
        closePanel1.add(jLabel10);
        jLabel10.setBounds(10, 10, 20, 20);

        jPanel1.add(closePanel1);
        closePanel1.setBounds(1050, 10, 40, 40);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        manageAdminButton.setBackground(new java.awt.Color(0, 0, 0));
        manageAdminButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manageAdminButton.setForeground(new java.awt.Color(255, 255, 255));
        manageAdminButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageAdminButton.setText("Manage Admin");
        manageAdminButton.setOpaque(true);
        manageAdminButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageAdminButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageAdminButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageAdminButtonMouseExited(evt);
            }
        });
        manageAdminButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                manageAdminButtonKeyPressed(evt);
            }
        });
        jPanel2.add(manageAdminButton);
        manageAdminButton.setBounds(0, 0, 120, 90);

        manageStudentButton.setBackground(new java.awt.Color(0, 0, 0));
        manageStudentButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manageStudentButton.setForeground(new java.awt.Color(255, 255, 255));
        manageStudentButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageStudentButton.setText("Manage Student");
        manageStudentButton.setOpaque(true);
        manageStudentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageStudentButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageStudentButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageStudentButtonMouseExited(evt);
            }
        });
        manageStudentButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                manageStudentButtonKeyPressed(evt);
            }
        });
        jPanel2.add(manageStudentButton);
        manageStudentButton.setBounds(0, 90, 120, 95);

        manageExamButton.setBackground(new java.awt.Color(0, 0, 0));
        manageExamButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manageExamButton.setForeground(new java.awt.Color(255, 255, 255));
        manageExamButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageExamButton.setText("Manage Exam");
        manageExamButton.setOpaque(true);
        manageExamButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageExamButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageExamButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageExamButtonMouseExited(evt);
            }
        });
        manageExamButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                manageExamButtonKeyPressed(evt);
            }
        });
        jPanel2.add(manageExamButton);
        manageExamButton.setBounds(0, 280, 120, 90);

        managePaperButton.setBackground(new java.awt.Color(0, 0, 0));
        managePaperButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        managePaperButton.setForeground(new java.awt.Color(255, 255, 255));
        managePaperButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        managePaperButton.setText("Manage Paper");
        managePaperButton.setOpaque(true);
        managePaperButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managePaperButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                managePaperButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                managePaperButtonMouseExited(evt);
            }
        });
        managePaperButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                managePaperButtonKeyPressed(evt);
            }
        });
        jPanel2.add(managePaperButton);
        managePaperButton.setBounds(0, 180, 120, 100);

        sendMessageButton.setBackground(new java.awt.Color(0, 0, 0));
        sendMessageButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sendMessageButton.setForeground(new java.awt.Color(255, 255, 255));
        sendMessageButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sendMessageButton.setText("Send Message");
        sendMessageButton.setOpaque(true);
        sendMessageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMessageButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendMessageButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendMessageButtonMouseExited(evt);
            }
        });
        sendMessageButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sendMessageButtonKeyPressed(evt);
            }
        });
        jPanel2.add(sendMessageButton);
        sendMessageButton.setBounds(0, 546, 120, 110);

        viewResultButton.setBackground(new java.awt.Color(0, 0, 0));
        viewResultButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewResultButton.setForeground(new java.awt.Color(255, 255, 255));
        viewResultButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewResultButton.setText("Vew Result");
        viewResultButton.setOpaque(true);
        viewResultButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewResultButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewResultButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewResultButtonMouseExited(evt);
            }
        });
        viewResultButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                viewResultButtonKeyPressed(evt);
            }
        });
        jPanel2.add(viewResultButton);
        viewResultButton.setBounds(0, 370, 120, 90);

        manageCourseButton.setBackground(new java.awt.Color(0, 0, 0));
        manageCourseButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        manageCourseButton.setForeground(new java.awt.Color(255, 255, 255));
        manageCourseButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageCourseButton.setText("Manage Course");
        manageCourseButton.setOpaque(true);
        manageCourseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageCourseButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageCourseButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageCourseButtonMouseExited(evt);
            }
        });
        manageCourseButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                manageCourseButtonKeyPressed(evt);
            }
        });
        jPanel2.add(manageCourseButton);
        manageCourseButton.setBounds(0, 460, 120, 90);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 50, 120, 650);

        settingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/settingButton.png"))); // NOI18N
        settingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingButtonMouseExited(evt);
            }
        });
        jPanel1.add(settingButton);
        settingButton.setBounds(150, 650, 50, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/title2.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 650, 1110, 50);

        hostPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/examSuccessLogo.jpg"))); // NOI18N

        javax.swing.GroupLayout hostPanelLayout = new javax.swing.GroupLayout(hostPanel);
        hostPanel.setLayout(hostPanelLayout);
        hostPanelLayout.setHorizontalGroup(
            hostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hostPanelLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        hostPanelLayout.setVerticalGroup(
            hostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        jPanel1.add(hostPanel);
        hostPanel.setBounds(120, 50, 990, 600);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Exam Simulater System");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 10, 570, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/title1.png"))); // NOI18N
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel8MouseDragged(evt);
            }
        });
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 1110, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageCourseButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manageCourseButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageCourseButtonKeyPressed

    private void manageCourseButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageCourseButtonMouseClicked
        relese.release();
        ManageCourse manageCourse = new ManageCourse(relese);
        hostPanel.removeAll();
        hostPanel.add(manageCourse);
        hostPanel.repaint();
        hostPanel.revalidate();
        manageCourse.setVisible(true);

    }//GEN-LAST:event_manageCourseButtonMouseClicked

    private void manageAdminButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAdminButtonMouseClicked
        relese.release();
        MainAdmin mainAdmin = new MainAdmin(relese);
        hostPanel.removeAll();
        hostPanel.add(mainAdmin);
        hostPanel.repaint();
        hostPanel.revalidate();
        mainAdmin.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_manageAdminButtonMouseClicked

    private void manageAdminButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manageAdminButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageAdminButtonKeyPressed

    private void manageStudentButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentButtonMouseClicked
        relese.release();
        MainStudent mainStudent = new MainStudent(relese);
        hostPanel.removeAll();
        hostPanel.add(mainStudent);
        hostPanel.repaint();
        hostPanel.revalidate();
        mainStudent.setVisible(true);
    }//GEN-LAST:event_manageStudentButtonMouseClicked

    private void manageStudentButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manageStudentButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageStudentButtonKeyPressed

    private void manageExamButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageExamButtonMouseClicked
        relese.release();
        ManageExam manageExam = new ManageExam(relese);
        hostPanel.removeAll();
        hostPanel.add(manageExam);
        hostPanel.repaint();
        hostPanel.revalidate();
        manageExam.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_manageExamButtonMouseClicked

    private void manageExamButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_manageExamButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageExamButtonKeyPressed

    private void managePaperButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managePaperButtonMouseClicked
        relese.release();
        ManageQuestion manageQuestion = new ManageQuestion(relese);
        hostPanel.removeAll();
        hostPanel.add(manageQuestion);
        hostPanel.repaint();
        hostPanel.revalidate();
        manageQuestion.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_managePaperButtonMouseClicked

    private void managePaperButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_managePaperButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_managePaperButtonKeyPressed

    private void sendMessageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMessageButtonMouseClicked
        relese.release();
        SendNotification sendNotification = new SendNotification();
        hostPanel.removeAll();
        hostPanel.add(sendNotification);
        hostPanel.repaint();
        hostPanel.revalidate();
        sendNotification.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_sendMessageButtonMouseClicked

    private void sendMessageButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sendMessageButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendMessageButtonKeyPressed

    private void viewResultButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewResultButtonMouseClicked
        relese.release();
        ViewAdminResult viewAdminResult = new ViewAdminResult();
        hostPanel.removeAll();
        hostPanel.add(viewAdminResult);
        hostPanel.repaint();
        hostPanel.revalidate();
        viewAdminResult.setVisible(true);
    }//GEN-LAST:event_viewResultButtonMouseClicked

    private void viewResultButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_viewResultButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewResultButtonKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            LoginController lc = ServerConnecter.getServerConnecter().getLoginController();
            lc.removeAdmin(id);
            relese.release();
            this.dispose();
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void minimizePanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizePanel1MouseClicked
        this.setState(Frame.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_minimizePanel1MouseClicked

    private void minimizePanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizePanel1MouseEntered
        minimizePanel1.setBackground(Color.pink);
    }//GEN-LAST:event_minimizePanel1MouseEntered

    private void minimizePanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizePanel1MouseExited
        minimizePanel1.setBackground(Color.white);
    }//GEN-LAST:event_minimizePanel1MouseExited

    private void closePanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closePanel1MouseClicked
        try {
            LoginController lc = ServerConnecter.getServerConnecter().getLoginController();
            lc.removeAdmin(id);
            relese.release();
            this.dispose();
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_closePanel1MouseClicked

    private void closePanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closePanel1MouseEntered
        closePanel1.setBackground(Color.pink); // TODO add your handling code here:
    }//GEN-LAST:event_closePanel1MouseEntered

    private void closePanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closePanel1MouseExited
        closePanel1.setBackground(Color.white);
    }//GEN-LAST:event_closePanel1MouseExited

    private void settingButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingButtonMouseClicked
        relese.release();
        if (setting == false) {
            AdminSetting ac = new AdminSetting(id, this);
            ac.setVisible(true);
            setting = true;
        }

    }//GEN-LAST:event_settingButtonMouseClicked

    private void settingButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingButtonMouseEntered
        settingButton.setBorder(new MotifBorders.BevelBorder(true, Color.RED, Color.RED));        // TODO add your handling code here:
    }//GEN-LAST:event_settingButtonMouseEntered

    private void settingButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingButtonMouseExited
        settingButton.setBorder(null);
    }//GEN-LAST:event_settingButtonMouseExited

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseDragged

    private void manageAdminButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAdminButtonMouseEntered
        manageAdminButton.setForeground(Color.black);
        manageAdminButton.setBackground(new Color(255, 204, 0));
    }//GEN-LAST:event_manageAdminButtonMouseEntered

    private void manageAdminButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageAdminButtonMouseExited
        manageAdminButton.setForeground(Color.white);
        manageAdminButton.setBackground(Color.black);
    }//GEN-LAST:event_manageAdminButtonMouseExited

    private void manageStudentButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentButtonMouseEntered
        manageStudentButton.setForeground(Color.black);
        manageStudentButton.setBackground(new Color(255, 204, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_manageStudentButtonMouseEntered

    private void managePaperButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managePaperButtonMouseEntered
        managePaperButton.setForeground(Color.black);
        managePaperButton.setBackground(new Color(255, 204, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_managePaperButtonMouseEntered

    private void manageExamButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageExamButtonMouseEntered
        manageExamButton.setForeground(Color.black);
        manageExamButton.setBackground(new Color(255, 204, 0));
    }//GEN-LAST:event_manageExamButtonMouseEntered

    private void viewResultButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewResultButtonMouseEntered
        viewResultButton.setForeground(Color.black);
        viewResultButton.setBackground(new Color(255, 204, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_viewResultButtonMouseEntered

    private void manageCourseButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageCourseButtonMouseEntered
        manageCourseButton.setForeground(Color.black);
        manageCourseButton.setBackground(new Color(255, 204, 0)); // TODO add your handling code here:
    }//GEN-LAST:event_manageCourseButtonMouseEntered

    private void sendMessageButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMessageButtonMouseEntered
        sendMessageButton.setForeground(Color.black);
        sendMessageButton.setBackground(new Color(255, 204, 0));
    }//GEN-LAST:event_sendMessageButtonMouseEntered

    private void manageStudentButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentButtonMouseExited
        manageStudentButton.setForeground(Color.white);
        manageStudentButton.setBackground(Color.black);
    }//GEN-LAST:event_manageStudentButtonMouseExited

    private void managePaperButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managePaperButtonMouseExited
        managePaperButton.setForeground(Color.white);
        managePaperButton.setBackground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_managePaperButtonMouseExited

    private void manageExamButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageExamButtonMouseExited
        manageExamButton.setForeground(Color.white);
        manageExamButton.setBackground(Color.black);
    }//GEN-LAST:event_manageExamButtonMouseExited

    private void viewResultButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewResultButtonMouseExited
        viewResultButton.setForeground(Color.white);
        viewResultButton.setBackground(Color.black);   // TODO add your handling code here:
    }//GEN-LAST:event_viewResultButtonMouseExited

    private void manageCourseButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageCourseButtonMouseExited
        manageCourseButton.setForeground(Color.white);
        manageCourseButton.setBackground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_manageCourseButtonMouseExited

    private void sendMessageButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendMessageButtonMouseExited
        sendMessageButton.setForeground(Color.white);
        sendMessageButton.setBackground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_sendMessageButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Admin().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel closePanel1;
    private javax.swing.JPanel hostPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel manageAdminButton;
    private javax.swing.JLabel manageCourseButton;
    private javax.swing.JLabel manageExamButton;
    private javax.swing.JLabel managePaperButton;
    private javax.swing.JLabel manageStudentButton;
    private javax.swing.JPanel minimizePanel1;
    private javax.swing.JLabel sendMessageButton;
    private javax.swing.JLabel settingButton;
    private javax.swing.JLabel viewResultButton;
    // End of variables declaration//GEN-END:variables
public boolean equals(Object ob) {
        if (ob instanceof Admin) {
            Admin a = (Admin) ob;
            return a.id == this.id;
        } else {
            return false;
        }
    }
}
