/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.examsuccess.view.admin;

import edu.ijse.gdse37.examsuccess.model.Admin;
import edu.ijse.gdse37.examsuccess.connecter.ServerConnecter;
import edu.ijse.gdse37.examsuccess.controller.AdminController;
import edu.ijse.gdse37.examsuccess.view.observerimpl.AdminObserverImpl;
import edu.ijse.gdse37.examsuccess.view.other.Relese;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ashan Tharuka
 */
public class View_Admin_Panal extends javax.swing.JPanel {

    /**
     * Creates new form AddQ_Panel_Form
     */
    private DefaultTableModel dtm;

    /**
     *
     * @param relese
     */
    public View_Admin_Panal(Relese relese) {
        initComponents();
        setSize(790, 600);
        dtm = (DefaultTableModel) view.getModel();
        dtm.setRowCount(0);

        try {
            AdminController ac = ServerConnecter.getServerConnecter().getAdminController();
            AdminObserverImpl admin = new AdminObserverImpl(this);
            relese.observerImplOb = admin;
            ac.addAdminObserver(admin);
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(View_Admin_Panal.class.getName()).log(Level.SEVERE, null, ex);
        }

        loardDate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        view = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(790, 600));
        setPreferredSize(new java.awt.Dimension(790, 600));
        setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("View Admin");
        add(jLabel6);
        jLabel6.setBounds(46, 24, 300, 55);

        view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Phone Number", "E Mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        view.setRowHeight(25);
        jScrollPane1.setViewportView(view);
        if (view.getColumnModel().getColumnCount() > 0) {
            view.getColumnModel().getColumn(0).setResizable(false);
            view.getColumnModel().getColumn(1).setResizable(false);
            view.getColumnModel().getColumn(2).setResizable(false);
            view.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(46, 116, 654, 357);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable view;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param message
     * updateMessage method
     */
    public void updateMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    /**
     *loardDate method
     */
    public void loardDate() {
        try {
            AdminController ac = ServerConnecter.getServerConnecter().getAdminController();
            ArrayList<Admin> addminList = ac.getAllAdmin();
            if (addminList == null) {
                JOptionPane.showMessageDialog(null, "No Admin Account");
            } else {
                for (Admin admin : addminList) {
                    Object[] row = {admin.getId(), admin.getName(), admin.getPhoneNumber(), admin.getEmail()};
                    dtm.addRow(row);
                }
            }

        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(View_Admin_Panal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(View_Admin_Panal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
