/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.examsuccess.view.manage;

import com.sun.java.swing.plaf.motif.MotifBorders;
import edu.ijse.gdse37.examsuccess.view.batch.BatchMain;
import edu.ijse.gdse37.examsuccess.view.cemester.CemesterMain;
import edu.ijse.gdse37.examsuccess.view.other.Relese;
import edu.ijse.gdse37.examsuccess.view.subject.SubjectMain;
import java.awt.Color;
import java.text.SimpleDateFormat;

/**
 *
 * @author Ashan Tharuka
 */
public class ManageCourse extends javax.swing.JPanel {

    private String path;
    private String fileName;
    private String date;
    private String time;
    private SimpleDateFormat sf;

    /**
     * Creates new form MainAdmin
     */
    private Relese relese;

    /**
     *
     * @param relese
     */
    public ManageCourse(Relese relese) {
        initComponents();
        setSize(990, 600);
        this.relese = relese;
        BatchMain ch = new BatchMain(relese);
        allPanel.removeAll();
        allPanel.add(ch);
        allPanel.repaint();
        allPanel.revalidate();
        ch.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        allPanel = new javax.swing.JPanel();
        subjectBtton = new javax.swing.JLabel();
        batchButton = new javax.swing.JLabel();
        cemsterButton = new javax.swing.JLabel();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        allPanel.setBackground(new java.awt.Color(255, 255, 255));
        allPanel.setMinimumSize(new java.awt.Dimension(780, 540));
        allPanel.setPreferredSize(new java.awt.Dimension(780, 540));
        allPanel.setLayout(null);
        jPanel1.add(allPanel);
        allPanel.setBounds(200, 20, 780, 540);

        subjectBtton.setBackground(new java.awt.Color(171, 227, 247));
        subjectBtton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        subjectBtton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subjectBtton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/courseButton.png"))); // NOI18N
        subjectBtton.setText("<html>Subject <br>");
        subjectBtton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        subjectBtton.setMinimumSize(new java.awt.Dimension(110, 50));
        subjectBtton.setPreferredSize(new java.awt.Dimension(110, 50));
        subjectBtton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subjectBttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subjectBttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subjectBttonMouseExited(evt);
            }
        });
        jPanel1.add(subjectBtton);
        subjectBtton.setBounds(20, 410, 160, 100);

        batchButton.setBackground(new java.awt.Color(171, 227, 247));
        batchButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        batchButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        batchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/courseButton.png"))); // NOI18N
        batchButton.setText("<html>Batch <br>");
        batchButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        batchButton.setMinimumSize(new java.awt.Dimension(110, 50));
        batchButton.setPreferredSize(new java.awt.Dimension(110, 50));
        batchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batchButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                batchButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                batchButtonMouseExited(evt);
            }
        });
        jPanel1.add(batchButton);
        batchButton.setBounds(20, 70, 160, 100);

        cemsterButton.setBackground(new java.awt.Color(171, 227, 247));
        cemsterButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cemsterButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cemsterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/courseButton.png"))); // NOI18N
        cemsterButton.setText("<html>Cemester <br>");
        cemsterButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cemsterButton.setMinimumSize(new java.awt.Dimension(110, 50));
        cemsterButton.setPreferredSize(new java.awt.Dimension(110, 50));
        cemsterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cemsterButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cemsterButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cemsterButtonMouseExited(evt);
            }
        });
        jPanel1.add(cemsterButton);
        cemsterButton.setBounds(20, 240, 160, 100);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 990, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void subjectBttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectBttonMouseClicked
        SubjectMain ch = new SubjectMain(relese);
        allPanel.removeAll();
        allPanel.add(ch);
        allPanel.repaint();
        allPanel.revalidate();
        ch.setVisible(true);
    }//GEN-LAST:event_subjectBttonMouseClicked

    private void subjectBttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectBttonMouseEntered
        subjectBtton.setBorder(new MotifBorders.BevelBorder(true, Color.white, Color.white));
        subjectBtton.setForeground(Color.white);
    }//GEN-LAST:event_subjectBttonMouseEntered

    private void subjectBttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subjectBttonMouseExited
        subjectBtton.setForeground(Color.black);
    }//GEN-LAST:event_subjectBttonMouseExited

    private void batchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batchButtonMouseClicked

        BatchMain ch = new BatchMain(relese);
        allPanel.removeAll();
        allPanel.add(ch);
        allPanel.repaint();
        allPanel.revalidate();
        ch.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_batchButtonMouseClicked

    private void batchButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batchButtonMouseEntered
        batchButton.setBorder(new MotifBorders.BevelBorder(true, Color.white, Color.white));
        batchButton.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_batchButtonMouseEntered

    private void batchButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batchButtonMouseExited
        batchButton.setForeground(Color.black);
    }//GEN-LAST:event_batchButtonMouseExited

    private void cemsterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cemsterButtonMouseClicked

        CemesterMain ch = new CemesterMain(relese);
        allPanel.removeAll();
        allPanel.add(ch);
        allPanel.repaint();
        allPanel.revalidate();
        ch.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cemsterButtonMouseClicked

    private void cemsterButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cemsterButtonMouseEntered
        cemsterButton.setBorder(new MotifBorders.BevelBorder(true, Color.white, Color.white));
        cemsterButton.setForeground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_cemsterButtonMouseEntered

    private void cemsterButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cemsterButtonMouseExited
        cemsterButton.setForeground(Color.black);
    }//GEN-LAST:event_cemsterButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allPanel;
    private javax.swing.JLabel batchButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cemsterButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel subjectBtton;
    // End of variables declaration//GEN-END:variables

}
