/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.examsuccess.view.manage;

import edu.ijse.gdse37.examsuccess.connecter.ServerConnecter;
import edu.ijse.gdse37.examsuccess.controller.StudentController;
import edu.ijse.gdse37.examsuccess.model.Student;
import java.awt.Color;
import java.awt.Frame;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Ashan Tharuka
 */
public class PracticeExamResultReport extends javax.swing.JFrame {

    private int xMouse;
    private int yMouse;
    private String path;
    private String fileName;
    private int startQ;
    private int endQ;
    private String studentId;
    private String practiceExamId;
    private String correctAns;
    private String wrongAns;
    private HashMap<String, String> studentAnswerList;
    private ArrayList<String> correctAnswerList;
    private ArrayList<String> resultList;

    /**
     * Creates new form Login
     *
     */
    public PracticeExamResultReport() {
        this.setUndecorated(true);
        setDefaultCloseOperation(2);
        this.setBackground(new Color(0, 255, 0, 0));
        initComponents();
        setLocationRelativeTo(null);
        setSize(1060, 401);

        //com.sun.awt.AWTUtilities.setWindowOpacity(this, 0.5f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        resultPanel2 = new javax.swing.JPanel();
        photoLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        paperNameLabel1 = new javax.swing.JLabel();
        correctAnsLabel1 = new javax.swing.JLabel();
        allQuestionLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        marksLabel = new javax.swing.JLabel();
        answerdQuestionsLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        gradeLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        wrongAnsLabel1 = new javax.swing.JLabel();
        resultPanel1 = new javax.swing.JPanel();
        photoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        paperNameLabel = new javax.swing.JLabel();
        correctAnsLabel = new javax.swing.JLabel();
        allQuestionLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        wrongAnsLabel = new javax.swing.JLabel();
        answerdQuestionsLabel = new javax.swing.JLabel();
        closePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        minimizePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        moreDetailButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1060, 401));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1060, 401));
        getContentPane().setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/resultPic.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 130, 170, 240);

        resultPanel2.setBackground(new java.awt.Color(255, 255, 255));
        resultPanel2.setLayout(null);
        resultPanel2.add(photoLabel1);
        photoLabel1.setBounds(20, 80, 150, 150);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("All Questions :");
        resultPanel2.add(jLabel8);
        jLabel8.setBounds(210, 310, 140, 40);

        nameLabel1.setFont(new java.awt.Font("Trajan Pro 3", 1, 24)); // NOI18N
        nameLabel1.setForeground(new java.awt.Color(0, 102, 102));
        nameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultPanel2.add(nameLabel1);
        nameLabel1.setBounds(20, 240, 150, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Paper Name :");
        resultPanel2.add(jLabel12);
        jLabel12.setBounds(210, 20, 140, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Correct Answers :");
        resultPanel2.add(jLabel13);
        jLabel13.setBounds(210, 60, 140, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/linePhoto.png"))); // NOI18N
        resultPanel2.add(jLabel14);
        jLabel14.setBounds(170, 0, 30, 310);

        paperNameLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paperNameLabel1.setForeground(new java.awt.Color(255, 0, 0));
        paperNameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resultPanel2.add(paperNameLabel1);
        paperNameLabel1.setBounds(360, 20, 90, 40);

        correctAnsLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        correctAnsLabel1.setForeground(new java.awt.Color(255, 0, 0));
        correctAnsLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resultPanel2.add(correctAnsLabel1);
        correctAnsLabel1.setBounds(360, 60, 90, 40);

        allQuestionLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        allQuestionLabel1.setForeground(new java.awt.Color(255, 0, 0));
        allQuestionLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resultPanel2.add(allQuestionLabel1);
        allQuestionLabel1.setBounds(360, 310, 90, 40);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Marks :");
        resultPanel2.add(jLabel15);
        jLabel15.setBounds(210, 110, 140, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Answered Question :");
        resultPanel2.add(jLabel16);
        jLabel16.setBounds(210, 260, 150, 40);

        marksLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        marksLabel.setForeground(new java.awt.Color(255, 0, 0));
        marksLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resultPanel2.add(marksLabel);
        marksLabel.setBounds(360, 110, 90, 40);

        answerdQuestionsLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        answerdQuestionsLabel1.setForeground(new java.awt.Color(255, 0, 0));
        answerdQuestionsLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resultPanel2.add(answerdQuestionsLabel1);
        answerdQuestionsLabel1.setBounds(360, 260, 90, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Grade :");
        resultPanel2.add(jLabel17);
        jLabel17.setBounds(210, 160, 140, 40);

        gradeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gradeLabel.setForeground(new java.awt.Color(255, 0, 0));
        gradeLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resultPanel2.add(gradeLabel);
        gradeLabel.setBounds(360, 160, 90, 40);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Wrong Answers :");
        resultPanel2.add(jLabel18);
        jLabel18.setBounds(210, 210, 140, 40);

        wrongAnsLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wrongAnsLabel1.setForeground(new java.awt.Color(255, 0, 0));
        wrongAnsLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resultPanel2.add(wrongAnsLabel1);
        wrongAnsLabel1.setBounds(360, 210, 90, 40);

        getContentPane().add(resultPanel2);
        resultPanel2.setBounds(420, 30, 460, 370);

        resultPanel1.setBackground(new java.awt.Color(255, 255, 255));
        resultPanel1.setLayout(null);
        resultPanel1.add(photoLabel);
        photoLabel.setBounds(20, 80, 150, 150);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("All Questions :");
        resultPanel1.add(jLabel1);
        jLabel1.setBounds(210, 290, 140, 40);

        nameLabel.setFont(new java.awt.Font("Trajan Pro 3", 1, 24)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 102, 102));
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultPanel1.add(nameLabel);
        nameLabel.setBounds(20, 240, 150, 50);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Paper Name :");
        resultPanel1.add(jLabel5);
        jLabel5.setBounds(210, 50, 140, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Correct Answers :");
        resultPanel1.add(jLabel6);
        jLabel6.setBounds(210, 110, 140, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/linePhoto.png"))); // NOI18N
        resultPanel1.add(jLabel9);
        jLabel9.setBounds(170, 0, 30, 310);

        paperNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paperNameLabel.setForeground(new java.awt.Color(255, 0, 0));
        paperNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resultPanel1.add(paperNameLabel);
        paperNameLabel.setBounds(360, 50, 90, 40);

        correctAnsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        correctAnsLabel.setForeground(new java.awt.Color(255, 0, 0));
        correctAnsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resultPanel1.add(correctAnsLabel);
        correctAnsLabel.setBounds(360, 110, 90, 40);

        allQuestionLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        allQuestionLabel.setForeground(new java.awt.Color(255, 0, 0));
        allQuestionLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resultPanel1.add(allQuestionLabel);
        allQuestionLabel.setBounds(360, 290, 90, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Wrong Answers :");
        resultPanel1.add(jLabel10);
        jLabel10.setBounds(210, 170, 140, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Answered Question :");
        resultPanel1.add(jLabel11);
        jLabel11.setBounds(210, 230, 150, 40);

        wrongAnsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        wrongAnsLabel.setForeground(new java.awt.Color(255, 0, 0));
        wrongAnsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resultPanel1.add(wrongAnsLabel);
        wrongAnsLabel.setBounds(360, 170, 90, 40);

        answerdQuestionsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        answerdQuestionsLabel.setForeground(new java.awt.Color(255, 0, 0));
        answerdQuestionsLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        resultPanel1.add(answerdQuestionsLabel);
        answerdQuestionsLabel.setBounds(360, 230, 90, 40);

        getContentPane().add(resultPanel1);
        resultPanel1.setBounds(420, 30, 460, 370);

        closePanel.setBackground(new java.awt.Color(255, 255, 255));
        closePanel.setForeground(new java.awt.Color(255, 255, 255));
        closePanel.setPreferredSize(new java.awt.Dimension(40, 40));
        closePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closePanelMouseExited(evt);
            }
        });
        closePanel.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/icon-nav-close.png"))); // NOI18N
        closePanel.add(jLabel3);
        jLabel3.setBounds(10, 10, 20, 20);

        getContentPane().add(closePanel);
        closePanel.setBounds(980, 40, 40, 40);

        minimizePanel.setBackground(new java.awt.Color(255, 255, 255));
        minimizePanel.setPreferredSize(new java.awt.Dimension(40, 40));
        minimizePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizePanelMouseExited(evt);
            }
        });
        minimizePanel.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/020739-rounded-glossy-black-icon-symbols-shapes-minimize.png"))); // NOI18N
        minimizePanel.add(jLabel4);
        jLabel4.setBounds(10, 20, 20, 10);

        getContentPane().add(minimizePanel);
        minimizePanel.setBounds(930, 40, 40, 40);

        moreDetailButton.setBackground(new java.awt.Color(171, 227, 247));
        moreDetailButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        moreDetailButton.setForeground(new java.awt.Color(255, 255, 255));
        moreDetailButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moreDetailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/blackButton.png"))); // NOI18N
        moreDetailButton.setText("<html>More Detail <br>");
        moreDetailButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        moreDetailButton.setMinimumSize(new java.awt.Dimension(110, 50));
        moreDetailButton.setPreferredSize(new java.awt.Dimension(110, 50));
        moreDetailButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moreDetailButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moreDetailButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moreDetailButtonMouseExited(evt);
            }
        });
        getContentPane().add(moreDetailButton);
        moreDetailButton.setBounds(880, 310, 170, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/image03.png"))); // NOI18N
        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 0, 943, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closePanelMouseClicked
        this.dispose();
    }//GEN-LAST:event_closePanelMouseClicked

    private void closePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closePanelMouseEntered
        closePanel.setBackground(Color.pink); // TODO add your handling code here:
    }//GEN-LAST:event_closePanelMouseEntered

    private void closePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closePanelMouseExited
        closePanel.setBackground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_closePanelMouseExited

    private void minimizePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizePanelMouseClicked
        this.setState(Frame.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_minimizePanelMouseClicked

    private void minimizePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizePanelMouseEntered
        minimizePanel.setBackground(Color.pink); // TODO add your handling code here:
    }//GEN-LAST:event_minimizePanelMouseEntered

    private void minimizePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizePanelMouseExited
        minimizePanel.setBackground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_minimizePanelMouseExited

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MousePressed

    private void moreDetailButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moreDetailButtonMouseClicked
        More_Exam_Result_Detail more = new More_Exam_Result_Detail(correctAnswerList, studentAnswerList, path, fileName, startQ, endQ, resultList);
        more.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_moreDetailButtonMouseClicked

    private void moreDetailButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moreDetailButtonMouseEntered
        moreDetailButton.setForeground(new Color(204, 255, 255));
    }//GEN-LAST:event_moreDetailButtonMouseEntered

    private void moreDetailButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moreDetailButtonMouseExited
        moreDetailButton.setForeground(Color.WHITE);          // TODO add your handling code here:
    }//GEN-LAST:event_moreDetailButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PracticeExamResultReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PracticeExamResultReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PracticeExamResultReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PracticeExamResultReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PracticeExamResultReport().setVisible(true);
            }
        });
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Practice_Exam().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allQuestionLabel;
    private javax.swing.JLabel allQuestionLabel1;
    private javax.swing.JLabel answerdQuestionsLabel;
    private javax.swing.JLabel answerdQuestionsLabel1;
    private javax.swing.JPanel closePanel;
    private javax.swing.JLabel correctAnsLabel;
    private javax.swing.JLabel correctAnsLabel1;
    private javax.swing.JLabel gradeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel marksLabel;
    private javax.swing.JPanel minimizePanel;
    private javax.swing.JLabel moreDetailButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel paperNameLabel;
    private javax.swing.JLabel paperNameLabel1;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JLabel photoLabel1;
    private javax.swing.JPanel resultPanel1;
    private javax.swing.JPanel resultPanel2;
    private javax.swing.JLabel wrongAnsLabel;
    private javax.swing.JLabel wrongAnsLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param path
     * @param fileName
     * @param studentId
     * @param correctAns
     * @param wrongAns
     * @param correctAnswersList
     * @param studentAnswerList
     * @param startQ
     * @param endQ
     * @param resultList
     */
    public void setData(String path, String fileName, String studentId, String correctAns, String wrongAns, ArrayList<String> correctAnswersList, HashMap<String, String> studentAnswerList, int startQ, int endQ, ArrayList<String> resultList) {
        resultPanel2.setVisible(false);
        resultPanel1.setVisible(true);
       
        this.path = path;
        this.fileName = fileName;
        this.studentId = studentId;
        this.practiceExamId = practiceExamId;
        this.correctAns = correctAns;
        this.wrongAns = wrongAns;
        this.correctAnswerList = correctAnswersList;
        this.studentAnswerList = studentAnswerList;
        this.startQ = startQ;
        this.endQ = endQ;
        this.resultList = resultList;
        // JOptionPane.showMessageDialog(null, studentAnswerList.get("1"));

        paperNameLabel.setText(fileName);
        correctAnsLabel.setText(correctAns);
        wrongAnsLabel.setText(wrongAns);
        answerdQuestionsLabel.setText(Integer.toString(Integer.parseInt(correctAns) + Integer.parseInt(wrongAns)));
        allQuestionLabel.setText(Integer.toString(correctAnswersList.size()));
        try {
            StudentController sc = ServerConnecter.getServerConnecter().getStudentController();
            Student student = sc.SearchStudent("id", studentId);
            nameLabel.setText(student.getName());
            photoLabel.setIcon(new ImageIcon(student.getImagePath()));
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(PracticeExamResultReport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PracticeExamResultReport.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     *
     * @param path
     * @param fileName
     * @param studentId
     * @param correctAns
     * @param wrongAns
     * @param correctAnswersList
     * @param studentAnswerList
     * @param startQ
     * @param endQ
     * @param resultList
     * @param grade
     * @param marks
     */
    public void setFinalExamData(String path, String fileName, String studentId, String correctAns, String wrongAns, ArrayList<String> correctAnswersList, HashMap<String, String> studentAnswerList, int startQ, int endQ, ArrayList<String> resultList, String grade, String marks) {
        resultPanel1.setVisible(false);
        resultPanel2.setVisible(true);
        
       
        this.path = path;
        this.fileName = fileName;
        this.studentId = studentId;
        this.practiceExamId = practiceExamId;
        this.correctAns = correctAns;
        this.wrongAns = wrongAns;
        this.correctAnswerList = correctAnswersList;
        this.studentAnswerList = studentAnswerList;
        this.startQ = startQ;
        this.endQ = endQ;
        this.resultList = resultList;
        // JOptionPane.showMessageDialog(null, studentAnswerList.get("1"));

        paperNameLabel1.setText(fileName);
        correctAnsLabel1.setText(correctAns);
        wrongAnsLabel1.setText(wrongAns);
        answerdQuestionsLabel1.setText(Integer.toString(Integer.parseInt(correctAns) + Integer.parseInt(wrongAns)));
        allQuestionLabel1.setText(Integer.toString(correctAnswersList.size()));
        marksLabel.setText(marks);
        gradeLabel.setText(grade);

        try {
            StudentController sc = ServerConnecter.getServerConnecter().getStudentController();
            Student student = sc.SearchStudent("id", studentId);
            nameLabel1.setText(student.getName());
            photoLabel1.setIcon(new ImageIcon(student.getImagePath()));
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(PracticeExamResultReport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PracticeExamResultReport.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
