/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.examsuccess.view.manage;

/**
 *
 * @author Ashan Tharuka
 */
public class SendNotification extends javax.swing.JPanel {

    /**
     * Creates new form MainAdmin
     */
    public SendNotification() {
        initComponents();
        setSize(990, 600);
        
        mailR.setSelected(true);
        boolean isTrue = mailR.isSelected();
        if (isTrue) {
            Email e = new Email();
            sendPanal.removeAll();
            sendPanal.add(e);
            sendPanal.repaint();
            sendPanal.revalidate();
            e.setVisible(true);
        } else {
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        sendPanal = new javax.swing.JPanel();
        mailR = new javax.swing.JRadioButton();
        notfiR = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        sendPanal.setBackground(new java.awt.Color(255, 255, 255));
        sendPanal.setMinimumSize(new java.awt.Dimension(800, 450));
        sendPanal.setPreferredSize(new java.awt.Dimension(800, 450));
        sendPanal.setLayout(null);
        jPanel1.add(sendPanal);
        sendPanal.setBounds(40, 110, 800, 450);

        mailR.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(mailR);
        mailR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mailR.setText("Send E mail");
        mailR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailRActionPerformed(evt);
            }
        });
        jPanel1.add(mailR);
        mailR.setBounds(40, 60, 130, 25);

        notfiR.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(notfiR);
        notfiR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        notfiR.setText("Send notification");
        notfiR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notfiRActionPerformed(evt);
            }
        });
        jPanel1.add(notfiR);
        notfiR.setBounds(240, 60, 180, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/emailSidePic.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(860, 0, 130, 600);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(0, 100, 990, 10);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 990, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void mailRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailRActionPerformed
        boolean isTrue = mailR.isSelected();
        if (isTrue) {
            Email e = new Email();
            sendPanal.removeAll();
            sendPanal.add(e);
            sendPanal.repaint();
            sendPanal.revalidate();
            e.setVisible(true);
        } else {
            
        }
    }//GEN-LAST:event_mailRActionPerformed

    private void notfiRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notfiRActionPerformed
        boolean isTrue = notfiR.isSelected();
        if (isTrue) {
            Notification n = new Notification();
            sendPanal.removeAll();
            sendPanal.add(n);
            sendPanal.repaint();
            sendPanal.revalidate();
            n.setVisible(true);
        } else {
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_notfiRActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton mailR;
    private javax.swing.JRadioButton notfiR;
    private javax.swing.JPanel sendPanal;
    // End of variables declaration//GEN-END:variables

}
