/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.examsuccess.view.manage;

import java.util.HashMap;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ashan Tharuka
 */
public class SummeryJPanel extends javax.swing.JPanel {

    private Practice_Exam ref;
    private Final_Exam ref2;
    private String status;
    private int count;

    /**
     * Creates new form SummeryJPanel
     * @param startQ
     * @param endQ
     * @param studentAnsList
     * @param ref
     */
    public SummeryJPanel(String startQ, String endQ, HashMap<String, String> studentAnsList, Practice_Exam ref) {
        initComponents();
        setSize(310, 380);
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0);
        this.ref = ref;
        status = "1";
        count = 0;

        for (int i = Integer.parseInt(startQ); i <= Integer.parseInt(endQ); i++) {
            ++count;
            if (studentAnsList.containsKey(Integer.toString(i))) {
                if (studentAnsList.get(Integer.toString(i)).equals("*:*:*:*")) {
                    System.out.println(i + " " + studentAnsList.get(Integer.toString(i)));
                    Object[] row1 = {i, "Not Answered"};
                    dtm.addRow(row1);
                } else {
                    System.out.println(i + " " + studentAnsList.get(Integer.toString(i)));
                    Object[] row2 = {i, "Answered"};
                    dtm.addRow(row2);
                }

            } else {
                System.out.println(i + " " + studentAnsList.get(Integer.toString(i)));
                Object[] row3 = {i, "Not Answered"};
                dtm.addRow(row3);
            }

        }
        System.out.println("/////////////////////////////////////////////////");
        ref.countSet(count);
    }

    /**
     *
     * @param startQ
     * @param endQ
     * @param studentAnsList
     * @param ref
     */
    public SummeryJPanel(String startQ, String endQ, HashMap<String, String> studentAnsList, Final_Exam ref) {
        initComponents();
        setSize(310, 320);
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        dtm.setRowCount(0);
        this.ref2 = ref;
        count = 0;

        status = "2";

        for (int i = Integer.parseInt(startQ); i <= Integer.parseInt(endQ); i++) {
            ++count;
            if (studentAnsList.containsKey(Integer.toString(i))) {
                if (studentAnsList.get(Integer.toString(i)).equals("*:*:*:*")) {
                    System.out.println(i + " " + studentAnsList.get(Integer.toString(i)));
                    Object[] row1 = {i, "Not Answered"};
                    dtm.addRow(row1);
                } else {
                    System.out.println(i + " " + studentAnsList.get(Integer.toString(i)));
                    Object[] row2 = {i, "Answered"};
                    dtm.addRow(row2);
                }

            } else {
                System.out.println(i + " " + studentAnsList.get(Integer.toString(i)));
                Object[] row3 = {i, "Not Answered"};
                dtm.addRow(row3);
            }

        }
        System.out.println("/////////////////////////////////////////////////");
        ref2.countSet(count);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(310, 320));
        setPreferredSize(new java.awt.Dimension(310, 320));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Question Number", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table.setRowHeight(25);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        if (status.equals("1")) {
            String id = table.getValueAt(table.getSelectedRow(), 0).toString();
            ref.goTo(Integer.parseInt(id));
            ref.assignValuetoQnumber(Integer.parseInt(id));
        } else {
            String id = table.getValueAt(table.getSelectedRow(), 0).toString();
            ref2.goTo(Integer.parseInt(id));
            ref2.assignValuetoQnumber(Integer.parseInt(id));
        }
    }//GEN-LAST:event_tableMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
