/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.examsuccess.view.student;

import com.sun.java.swing.plaf.motif.MotifBorders;
import edu.ijse.gdse37.examsuccess.view.manage.ViewSchedule;
import edu.ijse.gdse37.examsuccess.view.admin.Admin;
import edu.ijse.gdse37.examsuccess.connecter.ServerConnecter;
import edu.ijse.gdse37.examsuccess.controller.LoginController;
import edu.ijse.gdse37.examsuccess.view.manage.PracticeExamSchedule;
import edu.ijse.gdse37.examsuccess.view.manage.ViewStudentResult;
import edu.ijse.gdse37.examsuccess.view.other.Relese;
import java.awt.Color;
import java.awt.Frame;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ashan Tharuka
 */
public class Student extends javax.swing.JFrame {

    private static String id;
    private static String userName;

    private int xMouse;
    private int yMouse;

    private ArrayList<String> msgList;

    private int i;
    private Relese relese;

    /**
     * Creates new form Login
     *
     * @param id
     * @param userName
     */
    public Student(String id, String userName) {
        initComponents();
        setLocationRelativeTo(null);
        setSize(1105, 700);
        Student.id = id;
        Student.userName = userName;
        if (relese == null) {
            this.relese = new Relese();
        }

        msgList = new ArrayList<>();
        i = 0;
    }

    public boolean equals(Object ob) {
        if (ob instanceof Student) {
            Student s = (Student) ob;
            return Student.id == this.id;
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hostPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        countLabel = new javax.swing.JLabel();
        viewNotificationButton = new javax.swing.JLabel();
        closePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        minimizePanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        viewResultButton = new javax.swing.JLabel();
        practiceExamButton = new javax.swing.JLabel();
        examScheduleButton = new javax.swing.JLabel();
        updateUserButton = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1105, 621));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(null);

        hostPanel.setBackground(new java.awt.Color(255, 255, 255));
        hostPanel.setLayout(null);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/examSuccessLogo.jpg"))); // NOI18N
        hostPanel.add(jLabel12);
        jLabel12.setBounds(180, 0, 640, 600);

        jPanel1.add(hostPanel);
        hostPanel.setBounds(120, 50, 990, 600);

        countLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        countLabel.setForeground(new java.awt.Color(255, 0, 0));
        countLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(countLabel);
        countLabel.setBounds(170, 650, 30, 30);

        viewNotificationButton.setBackground(new java.awt.Color(255, 0, 0));
        viewNotificationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/msg_1.png"))); // NOI18N
        viewNotificationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewNotificationButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewNotificationButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewNotificationButtonMouseExited(evt);
            }
        });
        jPanel1.add(viewNotificationButton);
        viewNotificationButton.setBounds(140, 650, 60, 50);

        closePanel.setBackground(new java.awt.Color(255, 255, 255));
        closePanel.setForeground(new java.awt.Color(255, 255, 255));
        closePanel.setPreferredSize(new java.awt.Dimension(40, 40));
        closePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closePanelMouseExited(evt);
            }
        });
        closePanel.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/icon-nav-close.png"))); // NOI18N
        closePanel.add(jLabel2);
        jLabel2.setBounds(10, 10, 20, 20);

        jPanel1.add(closePanel);
        closePanel.setBounds(1050, 10, 40, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Exam Simulater System");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 10, 570, 30);

        minimizePanel1.setBackground(new java.awt.Color(255, 255, 255));
        minimizePanel1.setPreferredSize(new java.awt.Dimension(40, 40));
        minimizePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizePanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizePanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizePanel1MouseExited(evt);
            }
        });
        minimizePanel1.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/020739-rounded-glossy-black-icon-symbols-shapes-minimize.png"))); // NOI18N
        minimizePanel1.add(jLabel9);
        jLabel9.setBounds(10, 20, 20, 10);

        jPanel1.add(minimizePanel1);
        minimizePanel1.setBounds(1000, 10, 40, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/title1.png"))); // NOI18N
        jLabel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel8MouseDragged(evt);
            }
        });
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 1110, 50);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        viewResultButton.setBackground(new java.awt.Color(0, 0, 0));
        viewResultButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewResultButton.setForeground(new java.awt.Color(255, 255, 255));
        viewResultButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewResultButton.setText("View Result");
        viewResultButton.setOpaque(true);
        viewResultButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewResultButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewResultButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewResultButtonMouseExited(evt);
            }
        });
        viewResultButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                viewResultButtonKeyPressed(evt);
            }
        });
        jPanel2.add(viewResultButton);
        viewResultButton.setBounds(0, 270, 120, 90);

        practiceExamButton.setBackground(new java.awt.Color(0, 0, 0));
        practiceExamButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        practiceExamButton.setForeground(new java.awt.Color(255, 255, 255));
        practiceExamButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        practiceExamButton.setText("Practice Exam");
        practiceExamButton.setOpaque(true);
        practiceExamButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                practiceExamButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                practiceExamButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                practiceExamButtonMouseExited(evt);
            }
        });
        practiceExamButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                practiceExamButtonKeyPressed(evt);
            }
        });
        jPanel2.add(practiceExamButton);
        practiceExamButton.setBounds(0, 0, 120, 90);

        examScheduleButton.setBackground(new java.awt.Color(0, 0, 0));
        examScheduleButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        examScheduleButton.setForeground(new java.awt.Color(255, 255, 255));
        examScheduleButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        examScheduleButton.setText("Exam Schedule");
        examScheduleButton.setOpaque(true);
        examScheduleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                examScheduleButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                examScheduleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                examScheduleButtonMouseExited(evt);
            }
        });
        examScheduleButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                examScheduleButtonKeyPressed(evt);
            }
        });
        jPanel2.add(examScheduleButton);
        examScheduleButton.setBounds(0, 90, 120, 90);

        updateUserButton.setBackground(new java.awt.Color(0, 0, 0));
        updateUserButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateUserButton.setForeground(new java.awt.Color(255, 255, 255));
        updateUserButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateUserButton.setText("Update User");
        updateUserButton.setOpaque(true);
        updateUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateUserButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateUserButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateUserButtonMouseExited(evt);
            }
        });
        updateUserButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                updateUserButtonKeyPressed(evt);
            }
        });
        jPanel2.add(updateUserButton);
        updateUserButton.setBounds(0, 180, 120, 90);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 50, 120, 650);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/title2.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(0, 650, 1110, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1105, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            LoginController loginController = ServerConnecter.getServerConnecter().getLoginController();
            loginController.removeStudentObserver(id);
            relese.release();
            this.dispose();
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void closePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closePanelMouseClicked
        try {
            LoginController loginController = ServerConnecter.getServerConnecter().getLoginController();
            loginController.removeStudentObserver(id);
            relese.release();
            this.dispose();
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_closePanelMouseClicked

    private void closePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closePanelMouseEntered
        closePanel.setBackground(Color.pink); // TODO add your handling code here:
    }//GEN-LAST:event_closePanelMouseEntered

    private void closePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closePanelMouseExited
        closePanel.setBackground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_closePanelMouseExited

    private void viewNotificationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        relese.release();
        ViewNotification viewNotification = new ViewNotification(msgList, this);
        hostPanel.removeAll();
        hostPanel.add(viewNotification);
        hostPanel.repaint();
        hostPanel.revalidate();
        viewNotification.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void minimizePanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizePanel1MouseClicked
        this.setState(Frame.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_minimizePanel1MouseClicked

    private void minimizePanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizePanel1MouseEntered
        minimizePanel1.setBackground(Color.pink);
    }//GEN-LAST:event_minimizePanel1MouseEntered

    private void minimizePanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizePanel1MouseExited
        minimizePanel1.setBackground(Color.white);
    }//GEN-LAST:event_minimizePanel1MouseExited

    private void viewResultButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewResultButtonMouseClicked
        relese.release();
        ViewStudentResult viewStudentResult = new ViewStudentResult(id);
        hostPanel.removeAll();
        hostPanel.add(viewStudentResult);
        hostPanel.repaint();
        hostPanel.revalidate();
        viewStudentResult.setVisible(true);
    }//GEN-LAST:event_viewResultButtonMouseClicked

    private void viewResultButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_viewResultButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewResultButtonKeyPressed

    private void practiceExamButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_practiceExamButtonMouseClicked
        relese.release();
        PracticeExamSchedule practiceExamSchedule = new PracticeExamSchedule(id, this);
        hostPanel.removeAll();
        hostPanel.add(practiceExamSchedule);
        hostPanel.repaint();
        hostPanel.revalidate();
        practiceExamSchedule.setVisible(true);
    }//GEN-LAST:event_practiceExamButtonMouseClicked

    private void practiceExamButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_practiceExamButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_practiceExamButtonKeyPressed

    private void examScheduleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examScheduleButtonMouseClicked
        relese.release();
        ViewSchedule viewSchedule = new ViewSchedule(id, this);
        hostPanel.removeAll();
        hostPanel.add(viewSchedule);
        hostPanel.repaint();
        hostPanel.revalidate();
        viewSchedule.setVisible(true);
    }//GEN-LAST:event_examScheduleButtonMouseClicked

    private void examScheduleButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_examScheduleButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_examScheduleButtonKeyPressed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseDragged

    private void updateUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateUserButtonMouseClicked
        relese.release();
        Update_Student_Panal update_Student_Panal = new Update_Student_Panal(relese);
        hostPanel.removeAll();
        hostPanel.add(update_Student_Panal);
        hostPanel.repaint();
        hostPanel.revalidate();
        update_Student_Panal.setVisible(true);
    }//GEN-LAST:event_updateUserButtonMouseClicked

    private void updateUserButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_updateUserButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateUserButtonKeyPressed

    private void practiceExamButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_practiceExamButtonMouseEntered
        practiceExamButton.setForeground(Color.black);
        practiceExamButton.setBackground(new Color(255, 204, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_practiceExamButtonMouseEntered

    private void examScheduleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examScheduleButtonMouseEntered
        examScheduleButton.setForeground(Color.black);
        examScheduleButton.setBackground(new Color(255, 204, 0));
    }//GEN-LAST:event_examScheduleButtonMouseEntered

    private void updateUserButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateUserButtonMouseEntered
        updateUserButton.setForeground(Color.black);
        updateUserButton.setBackground(new Color(255, 204, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_updateUserButtonMouseEntered

    private void viewResultButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewResultButtonMouseEntered
        viewResultButton.setForeground(Color.black);
        viewResultButton.setBackground(new Color(255, 204, 0));          // TODO add your handling code here:
    }//GEN-LAST:event_viewResultButtonMouseEntered

    private void practiceExamButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_practiceExamButtonMouseExited
        practiceExamButton.setForeground(Color.white);
        practiceExamButton.setBackground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_practiceExamButtonMouseExited

    private void examScheduleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examScheduleButtonMouseExited
        examScheduleButton.setForeground(Color.white);
        examScheduleButton.setBackground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_examScheduleButtonMouseExited

    private void updateUserButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateUserButtonMouseExited
        updateUserButton.setForeground(Color.white);
        updateUserButton.setBackground(Color.black);         // TODO add your handling code here:
    }//GEN-LAST:event_updateUserButtonMouseExited

    private void viewResultButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewResultButtonMouseExited
        viewResultButton.setForeground(Color.white);
        viewResultButton.setBackground(Color.black);    // TODO add your handling code here:
    }//GEN-LAST:event_viewResultButtonMouseExited

    private void viewNotificationButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewNotificationButtonMouseEntered
      viewNotificationButton.setBorder(new MotifBorders.BevelBorder(true, Color.RED, Color.RED));               // TODO add your handling code here:
    }//GEN-LAST:event_viewNotificationButtonMouseEntered

    private void viewNotificationButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewNotificationButtonMouseExited
      viewNotificationButton.setBorder(null);
    }//GEN-LAST:event_viewNotificationButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Student().setVisible(true);
//            }
//        });
//        Student s = new Student("123", "");
//        s.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel closePanel;
    private javax.swing.JLabel countLabel;
    private javax.swing.JLabel examScheduleButton;
    private javax.swing.JPanel hostPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel minimizePanel1;
    private javax.swing.JLabel practiceExamButton;
    private javax.swing.JLabel updateUserButton;
    private javax.swing.JLabel viewNotificationButton;
    private javax.swing.JLabel viewResultButton;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param msg
     */
    public void setMessage(String msg) {
        ++i;
        countLabel.setText(Integer.toString(i));
        msgList.add(msg);
    }

    /**
     *
     */
    public void clearPanel() {
        hostPanel.removeAll();
        hostPanel.repaint();
    }

    /**
     *
     */
    public void clearCountLabel() {
        countLabel.setText(null);
    }

}
