/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.examsuccess.view.student;

import edu.ijse.gdse37.examsuccess.model.Batch;
import edu.ijse.gdse37.examsuccess.model.Student;
import edu.ijse.gdse37.examsuccess.view.other.ImageResizer;
import edu.ijse.gdse37.examsuccess.connecter.ServerConnecter;
import edu.ijse.gdse37.examsuccess.controller.BatchController;
import edu.ijse.gdse37.examsuccess.controller.StudentController;
import edu.ijse.gdse37.examsuccess.view.admin.Delete_Admin_Panal;
import edu.ijse.gdse37.examsuccess.view.other.Relese;
import edu.ijse.gdse37.examsuccess.view.other.Validation;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashan Tharuka
 */
public class Update_Student_Panal extends javax.swing.JPanel {

    private Student stu;
    private String imagePath;
    private Relese relese;
    private String code;

    /**
     * Creates new form AddQ_Panel_Form
     * @param relese
     */
    public Update_Student_Panal(Relese relese) {
        initComponents();
        setSize(770, 560);
        updateButton.setVisible(false);
        this.relese = relese;
        w3.setVisible(false);
        w2.setVisible(false);

        passText.setEnabled(false);
        veryPassText.setEditable(false);

        try {
            BatchController bc = ServerConnecter.getServerConnecter().getBatchController();
            ArrayList<Batch> allBatch = bc.getAllBatch();
            batchCombo.removeAll();
            for (Batch b : allBatch) {
                batchCombo.addItem(b.getBatchName());
            }
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(Add_Student_Panal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Add_Student_Panal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        passText = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        veryPassText = new javax.swing.JPasswordField();
        emailText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numberText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        w2 = new javax.swing.JLabel();
        updateButton = new javax.swing.JPanel();
        addLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        batchCombo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        oldPassText = new javax.swing.JPasswordField();
        w3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        parentEmailText = new javax.swing.JTextField();
        addPanel = new javax.swing.JPanel();
        photoLabel = new javax.swing.JLabel();
        attatchButton = new javax.swing.JLabel();
        pathLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(770, 560));
        setPreferredSize(new java.awt.Dimension(770, 560));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("New Password :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 420, 156, 30);

        passText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passTextKeyPressed(evt);
            }
        });
        jPanel1.add(passText);
        passText.setBounds(240, 420, 165, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Verify Password :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 470, 156, 30);

        veryPassText.setMinimumSize(new java.awt.Dimension(163, 30));
        veryPassText.setPreferredSize(new java.awt.Dimension(165, 30));
        veryPassText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                veryPassTextKeyReleased(evt);
            }
        });
        jPanel1.add(veryPassText);
        veryPassText.setBounds(240, 470, 165, 30);

        emailText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTextKeyReleased(evt);
            }
        });
        jPanel1.add(emailText);
        emailText.setBounds(240, 270, 163, 30);

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        nameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTextKeyReleased(evt);
            }
        });
        jPanel1.add(nameText);
        nameText.setBounds(240, 120, 163, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 120, 138, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Email :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 270, 150, 30);

        idText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextActionPerformed(evt);
            }
        });
        idText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idTextKeyReleased(evt);
            }
        });
        jPanel1.add(idText);
        idText.setBounds(240, 70, 163, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nic No :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 70, 93, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Batch :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 170, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Telephone Number :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 220, 141, 30);

        numberText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numberTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numberTextKeyReleased(evt);
            }
        });
        jPanel1.add(numberText);
        numberText.setBounds(240, 220, 163, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Update Student");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 0, 300, 55);

        w2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/w3Warning.png"))); // NOI18N
        jPanel1.add(w2);
        w2.setBounds(420, 480, 30, 20);

        updateButton.setBackground(new java.awt.Color(255, 255, 255));
        updateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        updateButton.setPreferredSize(new java.awt.Dimension(165, 40));
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateButtonMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                updateButtonMouseReleased(evt);
            }
        });
        updateButton.setLayout(null);

        addLabel.setFont(new java.awt.Font("Monotype.com", 1, 18)); // NOI18N
        addLabel.setText("Update");
        updateButton.add(addLabel);
        addLabel.setBounds(60, 0, 80, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/update.png"))); // NOI18N
        updateButton.add(jLabel16);
        jLabel16.setBounds(20, 0, 40, 40);

        jPanel1.add(updateButton);
        updateButton.setBounds(240, 510, 165, 40);

        jPanel1.add(batchCombo);
        batchCombo.setBounds(240, 170, 163, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Old Password :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 370, 156, 30);

        oldPassText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                oldPassTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                oldPassTextKeyReleased(evt);
            }
        });
        jPanel1.add(oldPassText);
        oldPassText.setBounds(240, 370, 165, 30);

        w3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/w3Warning.png"))); // NOI18N
        jPanel1.add(w3);
        w3.setBounds(420, 380, 20, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Parent Email :");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(80, 330, 95, 17);

        parentEmailText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                parentEmailTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                parentEmailTextKeyReleased(evt);
            }
        });
        jPanel1.add(parentEmailText);
        parentEmailText.setBounds(240, 320, 165, 30);

        addPanel.setBackground(new java.awt.Color(255, 255, 255));

        photoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        attatchButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        attatchButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        attatchButton.setText("Attach");
        attatchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        attatchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attatchButtonMouseClicked(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Attach Student Photo");

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(attatchButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(photoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pathLabel)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attatchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.add(addPanel);
        addPanel.setBounds(480, 80, 260, 230);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 780, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void veryPassTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_veryPassTextKeyReleased
        char[] password1 = passText.getPassword();
        char[] password2 = veryPassText.getPassword();
        String pass1 = String.valueOf(password1);
        String pass2 = String.valueOf(password2);
        if (pass1.equals(pass2)) {
            w2.setVisible(false);
            updateButton.setVisible(true);

        } else {
            w2.setVisible(true);
            updateButton.setVisible(false);
        }
    }//GEN-LAST:event_veryPassTextKeyReleased

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed

    }//GEN-LAST:event_nameTextActionPerformed

    private void nameTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyPressed
        Validation.name(nameText);
    }//GEN-LAST:event_nameTextKeyPressed

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        try {
            String pas = String.valueOf(veryPassText.getPassword());
            if (pas.isEmpty() && pas == null) {

            } else {
                String code = idText.getText();
                String name = nameText.getText();
                String batch = batchCombo.getSelectedItem().toString();
                String email = emailText.getText();
                String parentEmail = parentEmailText.getText();
                String number = numberText.getText();
                char[] password = veryPassText.getPassword();
                String pass = String.valueOf(password);

                if (imagePath == null) {
                    System.out.println("image null");
                    imagePath = stu.getImagePath();
                }

                Student student = new Student(code, name, batch, email, number, pass, parentEmail, imagePath);

                try {
                    StudentController sc = ServerConnecter.getServerConnecter().getStudentController();
                    boolean isTrue = sc.updateStudent(student);
                    if (isTrue) {
                        nameText.setText(null);
                        idText.setText(null);
                        emailText.setText(null);
                        numberText.setText(null);
                        passText.setText(null);
                        oldPassText.setText(null);
                        veryPassText.setText(null);
                        parentEmailText.setText(null);
                        JOptionPane.showMessageDialog(null, "Update Successfully");
                    } else {
                        JOptionPane.showMessageDialog(null, "Update Fail");
                    }
                } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                    Logger.getLogger(Update_Student_Panal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException | IOException ex) {
                    Logger.getLogger(Update_Student_Panal.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        } finally {
            try {
                StudentController studentController = ServerConnecter.getServerConnecter().getStudentController();
                studentController.releaseStudent(this.code);
            } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                Logger.getLogger(Delete_Admin_Panal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_updateButtonMouseClicked

    private void updateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseEntered
        updateButton.setBackground(Color.yellow);// TODO add your handling code here:
    }//GEN-LAST:event_updateButtonMouseEntered

    private void updateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseExited
        updateButton.setBackground(Color.white);        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonMouseExited

    private void updateButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonMouseReleased

    private void idTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextActionPerformed
        String code = idText.getText();
        relese.code = code;
        try {
            StudentController studentController = ServerConnecter.getServerConnecter().getStudentController();

            if (this.code != code) {
                studentController.releaseStudent(this.code);
            } else {
                this.code = code;
            }

            stu = studentController.SearchStudent("id", code);
            if (stu == null) {
                JOptionPane.showMessageDialog(null, "Not Match");

            } else {
                if (studentController.reserveStudent(code)) {
                    idText.setEditable(false);
                    nameText.setText(stu.getName());
                    emailText.setText(stu.getEmail());
                    batchCombo.setSelectedItem(stu.getBatch());
                    numberText.setText(stu.getPhoneNumber());
                    parentEmailText.setText(stu.getParentEmail());
                    photoLabel.setIcon(new ImageIcon(stu.getImagePath()));
                } else {
                    JOptionPane.showMessageDialog(this, code + " is reserved");
                }

            }
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(Delete_Student_Panal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Delete_Student_Panal.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_idTextActionPerformed

    private void oldPassTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oldPassTextKeyReleased
        String oldpass = String.valueOf(oldPassText.getPassword());
        if (oldpass.equals(stu.getPassword())) {
            w3.setVisible(false);
            passText.setEnabled(true);
            veryPassText.setEditable(true);

        } else {
            passText.setEnabled(false);
            veryPassText.setEditable(false);
            w3.setVisible(true);
        }
    }//GEN-LAST:event_oldPassTextKeyReleased

    private void passTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passTextKeyPressed

    }//GEN-LAST:event_passTextKeyPressed

    private void oldPassTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_oldPassTextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_oldPassTextKeyPressed

    private void attatchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attatchButtonMouseClicked
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            String fileName = f.getAbsolutePath();
            pathLabel.setText(fileName);

            ImageResizer imageResizer = new ImageResizer();
            imagePath = imageResizer.setImage(fileName, 130, 40, f.getName());

            photoLabel.setIcon(new ImageIcon(imagePath));
        } catch (NullPointerException ex) {
        }
    }//GEN-LAST:event_attatchButtonMouseClicked

    private void nameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTextKeyReleased
        Validation.name(nameText);        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextKeyReleased

    private void numberTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberTextKeyPressed
        Validation.phoneNumber(numberText);
    }//GEN-LAST:event_numberTextKeyPressed

    private void numberTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberTextKeyReleased
        Validation.phoneNumber(numberText);        // TODO add your handling code here:
    }//GEN-LAST:event_numberTextKeyReleased

    private void emailTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextKeyPressed
        Validation.email(emailText);
    }//GEN-LAST:event_emailTextKeyPressed

    private void emailTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTextKeyReleased
        Validation.email(emailText);
    }//GEN-LAST:event_emailTextKeyReleased

    private void parentEmailTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parentEmailTextKeyPressed
        Validation.email(parentEmailText);        // TODO add your handling code here:
    }//GEN-LAST:event_parentEmailTextKeyPressed

    private void parentEmailTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_parentEmailTextKeyReleased
        Validation.email(parentEmailText);         // TODO add your handling code here:
    }//GEN-LAST:event_parentEmailTextKeyReleased

    private void idTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextKeyPressed
        Validation.validationText(idText);
    }//GEN-LAST:event_idTextKeyPressed

    private void idTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextKeyReleased
        Validation.validationText(idText);        // TODO add your handling code here:
    }//GEN-LAST:event_idTextKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addLabel;
    private javax.swing.JPanel addPanel;
    private javax.swing.JLabel attatchButton;
    private javax.swing.JComboBox batchCombo;
    private javax.swing.JTextField emailText;
    private javax.swing.JTextField idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField numberText;
    private javax.swing.JPasswordField oldPassText;
    private javax.swing.JTextField parentEmailText;
    private javax.swing.JPasswordField passText;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JPanel updateButton;
    private javax.swing.JPasswordField veryPassText;
    private javax.swing.JLabel w2;
    private javax.swing.JLabel w3;
    // End of variables declaration//GEN-END:variables
}
