/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.examsuccess.view.student;

import edu.ijse.gdse37.examsuccess.view.admin.View_Admin_Panal;
import edu.ijse.gdse37.examsuccess.model.Student;
import edu.ijse.gdse37.examsuccess.connecter.ServerConnecter;
import edu.ijse.gdse37.examsuccess.controller.BatchController;
import edu.ijse.gdse37.examsuccess.controller.StudentController;
import edu.ijse.gdse37.examsuccess.model.Batch;
import edu.ijse.gdse37.examsuccess.view.manage.Email;
import edu.ijse.gdse37.examsuccess.view.observerimpl.StudentObserverImpl;
import edu.ijse.gdse37.examsuccess.view.other.Relese;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ashan Tharuka
 */
public class View_Student_Panal extends javax.swing.JPanel {

    /**
     * Creates new form AddQ_Panel_Form
     */
    private DefaultTableModel dtm;
    private String batch;

    /**
     *
     * @param relese
     */
    public View_Student_Panal(Relese relese) {
        initComponents();
        setSize(770, 560);
        dtm = (DefaultTableModel) view.getModel();
        dtm.setRowCount(0);
        view.setRowHeight(25);

        try {
            StudentController sc = ServerConnecter.getServerConnecter().getStudentController();
            StudentObserverImpl student = new StudentObserverImpl(this);
            relese.observerImplOb = student;
            sc.addStudentObserver(student);
        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(View_Student_Panal.class.getName()).log(Level.SEVERE, null, ex);
        }

        comboLoard();
        loardData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        view = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        batchCombo = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(770, 560));
        setPreferredSize(new java.awt.Dimension(770, 560));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Email", "Phone Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        view.setRowHeight(25);
        jScrollPane1.setViewportView(view);
        if (view.getColumnModel().getColumnCount() > 0) {
            view.getColumnModel().getColumn(0).setResizable(false);
            view.getColumnModel().getColumn(2).setResizable(false);
            view.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 180, 690, 310);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("View Students");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 20, 300, 55);

        batchCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                batchComboItemStateChanged(evt);
            }
        });
        batchCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batchComboMouseClicked(evt);
            }
        });
        batchCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchComboActionPerformed(evt);
            }
        });
        jPanel1.add(batchCombo);
        batchCombo.setBounds(60, 120, 90, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Batch");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(60, 100, 90, 15);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 820, 560);
    }// </editor-fold>//GEN-END:initComponents

    private void batchComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_batchComboItemStateChanged
        try {
            batch = batchCombo.getSelectedItem().toString();
            loardData();
        } catch (NullPointerException ex) {
        }
    }//GEN-LAST:event_batchComboItemStateChanged

    private void batchComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batchComboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_batchComboMouseClicked

    private void batchComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchComboActionPerformed
        try {
            batch = batchCombo.getSelectedItem().toString();
            loardData();

        } catch (NullPointerException ex) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_batchComboActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox batchCombo;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable view;
    // End of variables declaration//GEN-END:variables

    /**
     *
     */
     public void comboLoard() {
        try {
            BatchController bc = ServerConnecter.getServerConnecter().getBatchController();

            ////batch combo
            ArrayList<Batch> allBatch = bc.getAllBatch();
            batchCombo.removeAll();
            for (Batch b : allBatch) {
                batchCombo.addItem(b.getBatchName());
            }
        } catch (NotBoundException ex) {
            Logger.getLogger(Email.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Email.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(Email.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Email.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     *
     */
    public void loardData() {
        try {
            StudentController sc = ServerConnecter.getServerConnecter().getStudentController();
            ArrayList<Student> studenList = sc.getAllBatchStudents(batch);
            dtm.setRowCount(0);
            if (studenList == null) {
                JOptionPane.showMessageDialog(null, "No Students");
            } else {
                for (Student student : studenList) {
                    Object[] row = {student.getId(), student.getName(), student.getEmail(), student.getPhoneNumber()};
                    dtm.addRow(row);
                }
            }

        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(View_Admin_Panal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(View_Admin_Panal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     *
     * @param message
     */
    public void updateMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
}
