/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.examsuccess.view.batch;

import edu.ijse.gdse37.examsuccess.view.other.Relese;
import java.awt.Color;

/**
 *
 * @author Ashan Tharuka
 */
public class BatchMain extends javax.swing.JPanel {

    /**
     * Creates new form MainAdmin
     */
    private Relese relese;

    public BatchMain(Relese relese) {
        initComponents();
        setSize(780, 540);
        this.relese = relese;
        Add_Batch_Panal add_Batch_Panal = new Add_Batch_Panal();
        ccPanel.removeAll();
        ccPanel.add(add_Batch_Panal);
        ccPanel.repaint();
        ccPanel.revalidate();
        add_Batch_Panal.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ccPanel = new javax.swing.JPanel();
        viewButton = new javax.swing.JLabel();
        addButton = new javax.swing.JLabel();
        deleteButton = new javax.swing.JLabel();
        updateButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        ccPanel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ccPanel);
        ccPanel.setBounds(140, 50, 630, 480);

        viewButton.setBackground(new java.awt.Color(171, 227, 247));
        viewButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        viewButton.setForeground(new java.awt.Color(255, 255, 255));
        viewButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/courseButton2.png"))); // NOI18N
        viewButton.setText("<html>View <br>");
        viewButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewButton.setMinimumSize(new java.awt.Dimension(110, 50));
        viewButton.setPreferredSize(new java.awt.Dimension(110, 50));
        viewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewButtonMouseExited(evt);
            }
        });
        jPanel1.add(viewButton);
        viewButton.setBounds(10, 320, 120, 60);

        addButton.setBackground(new java.awt.Color(171, 227, 247));
        addButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/courseButton2.png"))); // NOI18N
        addButton.setText("<html>Add <br>");
        addButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addButton.setMinimumSize(new java.awt.Dimension(110, 50));
        addButton.setPreferredSize(new java.awt.Dimension(110, 50));
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addButtonMouseExited(evt);
            }
        });
        jPanel1.add(addButton);
        addButton.setBounds(10, 80, 120, 60);

        deleteButton.setBackground(new java.awt.Color(171, 227, 247));
        deleteButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/courseButton2.png"))); // NOI18N
        deleteButton.setText("<html>Delete <br>");
        deleteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteButton.setMinimumSize(new java.awt.Dimension(110, 50));
        deleteButton.setPreferredSize(new java.awt.Dimension(110, 50));
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteButtonMouseExited(evt);
            }
        });
        jPanel1.add(deleteButton);
        deleteButton.setBounds(10, 160, 120, 60);

        updateButton.setBackground(new java.awt.Color(171, 227, 247));
        updateButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/courseButton2.png"))); // NOI18N
        updateButton.setText("<html>Update <br>");
        updateButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        updateButton.setMinimumSize(new java.awt.Dimension(110, 50));
        updateButton.setPreferredSize(new java.awt.Dimension(110, 50));
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateButtonMouseExited(evt);
            }
        });
        jPanel1.add(updateButton);
        updateButton.setBounds(10, 240, 120, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Batch");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 0, 640, 40);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 780, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void viewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewButtonMouseClicked
        relese.release();
        View_Batch_Panal view_Batch_Panal = new View_Batch_Panal();
        ccPanel.removeAll();
        ccPanel.add(view_Batch_Panal);
        ccPanel.repaint();
        ccPanel.revalidate();
        view_Batch_Panal.setVisible(true);
    }//GEN-LAST:event_viewButtonMouseClicked

    private void viewButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewButtonMouseEntered
        viewButton.setForeground(new Color(204, 255, 255));
    }//GEN-LAST:event_viewButtonMouseEntered

    private void viewButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewButtonMouseExited
        viewButton.setForeground(Color.WHITE);          // TODO add your handling code here:
    }//GEN-LAST:event_viewButtonMouseExited

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        relese.release();
        Add_Batch_Panal add_Batch_Panal = new Add_Batch_Panal();
        ccPanel.removeAll();
        ccPanel.add(add_Batch_Panal);
        ccPanel.repaint();
        ccPanel.revalidate();
        add_Batch_Panal.setVisible(true);
    }//GEN-LAST:event_addButtonMouseClicked

    private void addButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseEntered
        addButton.setForeground(new Color(204, 255, 255));        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonMouseEntered

    private void addButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseExited
        addButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_addButtonMouseExited

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        relese.release();
        Delete_Batch_Panal delete_Batch_Panal = new Delete_Batch_Panal(relese);
        ccPanel.removeAll();
        ccPanel.add(delete_Batch_Panal);
        ccPanel.repaint();
        ccPanel.revalidate();
        delete_Batch_Panal.setVisible(true);
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void deleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseEntered
        deleteButton.setForeground(new Color(204, 255, 255));        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonMouseEntered

    private void deleteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseExited
        deleteButton.setForeground(Color.WHITE);           // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonMouseExited

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        relese.release();
        Update_Batch_Panal update_Batch_Panal = new Update_Batch_Panal(relese);
        ccPanel.removeAll();
        ccPanel.add(update_Batch_Panal);
        ccPanel.repaint();
        ccPanel.revalidate();
        update_Batch_Panal.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonMouseClicked

    private void updateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseEntered
        updateButton.setForeground(new Color(204, 255, 255));        // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonMouseEntered

    private void updateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseExited
        updateButton.setForeground(Color.WHITE);           // TODO add your handling code here:
    }//GEN-LAST:event_updateButtonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addButton;
    private javax.swing.JPanel ccPanel;
    private javax.swing.JLabel deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel updateButton;
    private javax.swing.JLabel viewButton;
    // End of variables declaration//GEN-END:variables
}
