/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.gdse37.examsuccess.view.login;

import edu.ijse.gdse37.examsuccess.view.student.Student;
import edu.ijse.gdse37.examsuccess.view.admin.Admin;
import edu.ijse.gdse37.examsuccess.view.observerimpl.ExamSimulaterObserverImpl;
import com.sun.xml.internal.messaging.saaj.packaging.mime.MessagingException;
import edu.ijse.gdse37.examsuccess.connecter.ServerConnecter;
import edu.ijse.gdse37.examsuccess.controller.AdminController;
import edu.ijse.gdse37.examsuccess.controller.LoginController;
import edu.ijse.gdse37.examsuccess.controller.StudentController;
import java.awt.Color;
import java.awt.Frame;
import AppPackage.AnimationClass;
import edu.ijse.gdse37.examsuccess.view.other.Validation;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ashan Tharuka
 */
public class Login extends javax.swing.JFrame {

    private int xMouse;
    private int yMouse;
    /**
     * Creates new form Login
     */
    AnimationClass ac = new AnimationClass();

    /**
     *
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(1105, 700);
        setLocationRelativeTo(null);
        //////////////////////////////////
        typeCombo2.setVisible(false);
        idText2.setVisible(false);
        sendButton.setVisible(false);
        w3.setVisible(false);
        sentLabel2.setVisible(false);

        //////////////////////////////////
        w1.setVisible(false);
        w2.setVisible(false);

        slideShow();

    }

    /**
     *
     */
    public void slideShow() {
        new Thread() {
            int count = 0;

            @Override
            public void run() {

                try {
                    while (true) {
                        if (count == 0) {
                            Thread.sleep(4000);
                            backGroundLabel1.setIcon(new ImageIcon(getClass().getResource("../photos/back3.png")));
                            backGroundLabel2.setIcon(new ImageIcon(getClass().getResource("../photos/back2.png")));
                            ac.jLabelXLeft(0, -1110, 35, 10, backGroundLabel1);
                            ac.jLabelXLeft(1110, 0, 35, 10, backGroundLabel2);

                            count = 1;
                        } else if (count == 1) {
                            Thread.sleep(4000);
                            backGroundLabel1.setIcon(new ImageIcon(getClass().getResource("../photos/back1.png")));
                            backGroundLabel2.setIcon(new ImageIcon(getClass().getResource("../photos/back4.png")));
                            ac.jLabelXRight(-1110, 0, 35, 10, backGroundLabel1);
                            ac.jLabelXRight(0, 1110, 35, 10, backGroundLabel2);

                            count = 0;
                        } //else if (count == 1) {
//                            backGroundLabel1.setIcon(new ImageIcon(getClass().getResource("../Photos/back3.png")));
//                            Thread.sleep(4000);
//                            ac.jLabelXLeft(0, -1110, 30, 10, backGroundLabel1);
//                            ac.jLabelXLeft(1110, 0, 30, 10, backGroundLabel2);
//                            count = 0;
//                        }

//                              
                    }
                } catch (Exception ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        idText2 = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        loginPhotoLabel = new javax.swing.JLabel();
        loginButon = new javax.swing.JLabel();
        forgotButton = new javax.swing.JLabel();
        typeCombo2 = new javax.swing.JComboBox();
        typeCombo = new javax.swing.JComboBox();
        idText = new javax.swing.JTextField();
        sendButton = new javax.swing.JLabel();
        sentLabel2 = new javax.swing.JLabel();
        w2 = new javax.swing.JLabel();
        w1 = new javax.swing.JLabel();
        w3 = new javax.swing.JLabel();
        panelLabel = new javax.swing.JLabel();
        minimizePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        closePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        backGroundLabel2 = new javax.swing.JLabel();
        backGroundLabel1 = new javax.swing.JLabel();
        backGroundLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1105, 700));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        idText2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idText2FocusGained(evt);
            }
        });
        idText2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idText2KeyReleased(evt);
            }
        });
        jPanel2.add(idText2);
        idText2.setBounds(180, 340, 110, 20);

        passwordText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passwordText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTextKeyPressed(evt);
            }
        });
        jPanel2.add(passwordText);
        passwordText.setBounds(60, 200, 230, 30);

        loginPhotoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/logLabel.png"))); // NOI18N
        jPanel2.add(loginPhotoLabel);
        loginPhotoLabel.setBounds(60, 40, 230, 50);

        loginButon.setBackground(new java.awt.Color(0, 102, 255));
        loginButon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginButon.setForeground(new java.awt.Color(255, 255, 255));
        loginButon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginButon.setText("Log In");
        loginButon.setOpaque(true);
        loginButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButonMouseClicked(evt);
            }
        });
        jPanel2.add(loginButon);
        loginButon.setBounds(60, 240, 230, 40);

        forgotButton.setBackground(new java.awt.Color(0, 0, 0));
        forgotButton.setForeground(new java.awt.Color(255, 255, 255));
        forgotButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotButton.setText("Forgot Password?");
        forgotButton.setOpaque(true);
        forgotButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                forgotButtonMouseEntered(evt);
            }
        });
        jPanel2.add(forgotButton);
        forgotButton.setBounds(60, 310, 100, 20);

        typeCombo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Student" }));
        jPanel2.add(typeCombo2);
        typeCombo2.setBounds(180, 310, 110, 20);

        typeCombo.setBackground(new java.awt.Color(102, 102, 255));
        typeCombo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        typeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Student" }));
        jPanel2.add(typeCombo);
        typeCombo.setBounds(60, 110, 230, 30);

        idText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        idText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                idTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idTextKeyReleased(evt);
            }
        });
        jPanel2.add(idText);
        idText.setBounds(60, 150, 230, 30);

        sendButton.setBackground(new java.awt.Color(0, 0, 0));
        sendButton.setForeground(new java.awt.Color(255, 255, 255));
        sendButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sendButton.setText("Send Mail");
        sendButton.setOpaque(true);
        sendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendButtonMouseClicked(evt);
            }
        });
        jPanel2.add(sendButton);
        sendButton.setBounds(180, 370, 110, 20);

        sentLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sentLabel2.setText("Email Sent");
        jPanel2.add(sentLabel2);
        sentLabel2.setBounds(60, 340, 80, 20);

        w2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/w3Warning.png"))); // NOI18N
        jPanel2.add(w2);
        w2.setBounds(300, 200, 30, 30);

        w1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/w3Warning.png"))); // NOI18N
        jPanel2.add(w1);
        w1.setBounds(300, 150, 30, 30);

        w3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/w3Warning.png"))); // NOI18N
        jPanel2.add(w3);
        w3.setBounds(300, 370, 20, 20);

        panelLabel.setBackground(new java.awt.Color(51, 51, 255));
        panelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/loginBack.png"))); // NOI18N
        jPanel2.add(panelLabel);
        panelLabel.setBounds(0, 0, 350, 430);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(50, 150, 350, 430);

        minimizePanel.setBackground(new java.awt.Color(255, 255, 255));
        minimizePanel.setPreferredSize(new java.awt.Dimension(40, 40));
        minimizePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizePanelMouseExited(evt);
            }
        });
        minimizePanel.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/020739-rounded-glossy-black-icon-symbols-shapes-minimize.png"))); // NOI18N
        minimizePanel.add(jLabel3);
        jLabel3.setBounds(10, 20, 20, 10);

        getContentPane().add(minimizePanel);
        minimizePanel.setBounds(1000, 10, 40, 40);

        closePanel.setBackground(new java.awt.Color(255, 255, 255));
        closePanel.setForeground(new java.awt.Color(255, 255, 255));
        closePanel.setPreferredSize(new java.awt.Dimension(40, 40));
        closePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closePanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closePanelMouseExited(evt);
            }
        });
        closePanel.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/icon-nav-close.png"))); // NOI18N
        closePanel.add(jLabel2);
        jLabel2.setBounds(10, 10, 20, 20);

        getContentPane().add(closePanel);
        closePanel.setBounds(1050, 10, 40, 40);

        backGroundLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/back2.png"))); // NOI18N
        backGroundLabel2.setName(""); // NOI18N
        getContentPane().add(backGroundLabel2);
        backGroundLabel2.setBounds(1110, 50, 1110, 600);

        backGroundLabel1.setBackground(new java.awt.Color(0, 0, 0));
        backGroundLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/back1.png"))); // NOI18N
        getContentPane().add(backGroundLabel1);
        backGroundLabel1.setBounds(0, 50, 1110, 600);

        backGroundLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/back3.png"))); // NOI18N
        backGroundLabel3.setMaximumSize(new java.awt.Dimension(1105, 600));
        backGroundLabel3.setMinimumSize(new java.awt.Dimension(1105, 600));
        backGroundLabel3.setPreferredSize(new java.awt.Dimension(1105, 600));
        getContentPane().add(backGroundLabel3);
        backGroundLabel3.setBounds(-1110, 50, 1105, 600);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/title2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 650, 1110, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/gdse37/examsuccess/view/photos/title1.png"))); // NOI18N
        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel6MouseDragged(evt);
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 1110, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendButtonMouseClicked
        boolean isTrue = false;
        String id = idText2.getText();
        String type = typeCombo2.getSelectedItem().toString();

        if (type.equals("Student")) {
            if (id == null && id.isEmpty()) {
                w3.setVisible(true);
            } else {
                w3.setVisible(false);
                try {
                    StudentController sc = ServerConnecter.getServerConnecter().getStudentController();
                    isTrue = sc.searchId(id);

                } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (isTrue) {

                    w3.setVisible(false);
                    try {
                        StudentController sc = ServerConnecter.getServerConnecter().getStudentController();
                        AdminController ac = ServerConnecter.getServerConnecter().getAdminController();
                        LoginController lc = ServerConnecter.getServerConnecter().getLoginController();

                        String[] instituteEmail = ac.getInstitueEmailPassword().split(":");
                        System.out.println("institue Email Password : " + instituteEmail);
                        String email = sc.getEmail(id);
                        String pass = sc.getPasword(id);
                        String msg = "Your Password :" + pass;
                        boolean isSend = lc.sendMailTo(email, "Student Account Password ", msg, instituteEmail[0], instituteEmail[1]);

                        if (isSend) {
                            sentLabel2.setVisible(true);

                            w3.setVisible(false);
                        } else {
                        }

                        typeCombo2.setVisible(false);
                        idText2.setVisible(false);
                        sendButton.setVisible(false);
                        w3.setVisible(false);
                    } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (javax.mail.MessagingException ex) {
                        JOptionPane.showMessageDialog(null, "Couldn't Connect internet", "Warning", 2);
                    } catch (MessagingException ex) {
                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {

                    w3.setVisible(true);
                }
            }
        } else {
            if (id == null && id.isEmpty()) {
                w3.setVisible(true);
            } else {

                w3.setVisible(false);
                try {

                    AdminController sc = ServerConnecter.getServerConnecter().getAdminController();
                    isTrue = sc.searchId(id);

                } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (isTrue) {

                    w3.setVisible(false);
                    try {
                        // sc = ServerConnecter.getServerConnecter().getStudentController();
                        AdminController ac = ServerConnecter.getServerConnecter().getAdminController();
                        LoginController lc = ServerConnecter.getServerConnecter().getLoginController();

                        String[] instituteEmail = ac.getInstitueEmailPassword().split(":");
                        System.out.println("institue Email Password : " + instituteEmail);
                        String email = ac.getEmail(id);
                        String pass = ac.getPasword(id);
                        String msg = "Your Password :" + pass;
                        boolean isSend = lc.sendMailTo(email, "Admin Account Password ", msg, instituteEmail[0], instituteEmail[1]);

                        if (isSend) {
                            sentLabel2.setVisible(true);

                            w3.setVisible(false);
                        } else {
                        }

                        typeCombo2.setVisible(false);
                        idText2.setVisible(false);
                        sendButton.setVisible(false);
                        w3.setVisible(false);
                    } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                    } catch (javax.mail.MessagingException ex) {
                        //ex.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Couldn't Connect internet", "Warning", 2);
                    } catch (MessagingException ex) {
                      //  ex.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Couldn't Connect internet", "Warning", 2);
                    }
                } else {

                    w3.setVisible(true);
                }

            }
        }
    }//GEN-LAST:event_sendButtonMouseClicked

    private void forgotButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotButtonMouseClicked
        typeCombo2.setVisible(true);
        idText2.setVisible(true);
        sendButton.setVisible(true);
    }//GEN-LAST:event_forgotButtonMouseClicked

    private void loginButonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButonMouseClicked
        String type = typeCombo.getSelectedItem().toString();
        String id = idText.getText();
        String pass = String.valueOf(passwordText.getPassword());

        if (type.equals("Student")) {
            try {
                StudentController sc = ServerConnecter.getServerConnecter().getStudentController();
                ////check student already in or out
                LoginController lc = ServerConnecter.getServerConnecter().getLoginController();
                boolean isIn = lc.registerIdIsAvaiable(id);
                boolean checkPassword = sc.checkPassword(id, pass);
                if (checkPassword) {
                    if (isIn) {
                        JOptionPane.showMessageDialog(null, "Student Account Already have Created", "Wanrning !!!", 2);
                        idText.setText(null);
                        passwordText.setText(null);
                    } else {
                        w2.setVisible(false);
                        System.out.println("sss");
                        makeNewWindow();
                        this.dispose();
                    }

                } else {
                    w2.setVisible(true);
                    passwordText.setText(null);
                }
            } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                AdminController ac = ServerConnecter.getServerConnecter().getAdminController();
                ////check Admin already in or out
                LoginController lc = ServerConnecter.getServerConnecter().getLoginController();
                boolean isIn = lc.AdminIdIsAvaiable(id);
                boolean checkPassword = ac.checkPassword(id, pass);

                if (checkPassword) {
                    if (isIn) {
                        JOptionPane.showMessageDialog(null, "Admin Account Already have Created", "Wanrning !!!", 2);
                        idText.setText(null);
                        passwordText.setText(null);
                    } else {
                        w2.setVisible(false);
                        String name = ac.getName(id);
                        new Admin(id, name).setVisible(true);
                        lc.addAdminOnlineList(id);
                        this.dispose();

                    }

                } else {
                    w2.setVisible(true);
                    passwordText.setText(null);
                }
            } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_loginButonMouseClicked

    private void passwordTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTextKeyPressed
        String type = typeCombo.getSelectedItem().toString();
        String id = idText.getText();

        if (type.equals("Student")) {
            try {
                StudentController sm = ServerConnecter.getServerConnecter().getStudentController();
                boolean searchId = sm.searchId(id);
                if (searchId) {
                    w1.setVisible(false);

                } else {
                    w1.setVisible(true);
                }
            } catch (NotBoundException | MalformedURLException | RemoteException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                AdminController am = ServerConnecter.getServerConnecter().getAdminController();
                boolean searchId = am.searchId(id);
                if (searchId) {
                    w1.setVisible(false);
                } else {
                    w1.setVisible(true);
                }
            } catch (NotBoundException | MalformedURLException | RemoteException | NullPointerException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_passwordTextKeyPressed

    private void idText2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idText2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_idText2FocusGained

    private void closePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closePanelMouseExited
        closePanel.setBackground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_closePanelMouseExited

    private void closePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closePanelMouseEntered
        closePanel.setBackground(Color.pink); // TODO add your handling code here:
    }//GEN-LAST:event_closePanelMouseEntered

    private void closePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closePanelMouseClicked
        this.dispose();
    }//GEN-LAST:event_closePanelMouseClicked

    private void minimizePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizePanelMouseExited
        minimizePanel.setBackground(Color.white);  // TODO add your handling code here:
    }//GEN-LAST:event_minimizePanelMouseExited

    private void minimizePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizePanelMouseEntered
        minimizePanel.setBackground(Color.pink); // TODO add your handling code here:
    }//GEN-LAST:event_minimizePanelMouseEntered

    private void minimizePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizePanelMouseClicked
        this.setState(Frame.ICONIFIED);// TODO add your handling code here:
    }//GEN-LAST:event_minimizePanelMouseClicked

    private void idTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextKeyReleased
        Validation.validationText(idText);
    }//GEN-LAST:event_idTextKeyReleased

    private void idTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextKeyPressed
        Validation.validationText(idText);        // TODO add your handling code here:
    }//GEN-LAST:event_idTextKeyPressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();            // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);          // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseDragged

    private void forgotButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_forgotButtonMouseEntered

    private void idText2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idText2KeyReleased
        Validation.validationText(idText2);
    }//GEN-LAST:event_idText2KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGroundLabel1;
    private javax.swing.JLabel backGroundLabel2;
    private javax.swing.JLabel backGroundLabel3;
    private javax.swing.JPanel closePanel;
    private javax.swing.JLabel forgotButton;
    private javax.swing.JTextField idText;
    private javax.swing.JTextField idText2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel loginButon;
    private javax.swing.JLabel loginPhotoLabel;
    private javax.swing.JPanel minimizePanel;
    private javax.swing.JLabel panelLabel;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JLabel sendButton;
    private javax.swing.JLabel sentLabel2;
    private javax.swing.JComboBox typeCombo;
    private javax.swing.JComboBox typeCombo2;
    private javax.swing.JLabel w1;
    private javax.swing.JLabel w2;
    private javax.swing.JLabel w3;
    // End of variables declaration//GEN-END:variables

    /**
     * makeNewWindow for user
     */
    public void makeNewWindow() {
        System.out.println("make window");
        String id = idText.getText();
        try {
            LoginController lc = ServerConnecter.getServerConnecter().getLoginController();
            StudentController sc = ServerConnecter.getServerConnecter().getStudentController();
            String name = sc.getName(id);
            Student s = new Student(id, name);
            s.setVisible(true);
            ExamSimulaterObserverImpl impl = new ExamSimulaterObserverImpl(s);
            lc.addStudentObserver(id, impl);

        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
